In [2]:
"""
This cell imports all the necessary 3rd party libraries and loads our scouted matches
"""

import pandas as pd
pd.set_option('display.max_columns', None)

scouted_data = df = pd.read_csv("data/scouted_data.csv")

In [3]:
"""
Step 1.

"print" the scouted data dataframe. You can either explicitly print() it, or just have it be the last item in the cell
"""

scouted_data

,org_key,year,event_key,match_key,match_number,time,alliance,team_key,totalAutoPoints,totalTeleopPoints,totalEndgamePoints,contributedPoints,totalAutoCoral,totalTeleopCoral,totalCoral,totalAutoAlgae,totalTeleopAlgae,totalAlgae,ClimbTime,Reliability,startingPosition,didLeaveStartingZone,autoCoralL4,autoCoralL3,autoCoralL2,autoCoralL1,autoAlgaeProc,autoAlgaeNet,teleopCoralL4,teleopCoralL3,teleopCoralL2,teleopCoralL1,teleopAlgaeProc,teleopAlgaeNet,didDefense,Defenserating,totalMinorFouls,totalMajorFouls,climbingStartTime,climbingStopTime,bargeStatus,diedDuringMatch,recoveredFromFreeze,didYellowCard,didRedCard
0,frc4467,2025,2025tnkn,2025tnkn_qm1,1,4/4/2025 12:50:00 PM,blue,frc21,10,29,12,51,1,7,8,0,0,0,16,1.0,Cage Side,1,1,0,0,0,0,0,3,3,0,1,0,0,0,0,0,0,21,5,Deep Cage,0,0,0,0
1,frc4467,2025,2025tnkn,2025tnkn_qm1,1,4/4/2025 12:50:00 PM,blue,frc3824,6,18,12,36,1,2,3,0,3,3,20,1.0,Middle,1,0,0,0,1,0,0,0,1,0,1,0,3,0,0,0,0,20,0,Deep Cage,0,0,0,0
2,frc4467,2025,2025tnkn,2025tnkn_qm1,1,4/4/2025 12:50:00 PM,red,frc5045,0,4,0,4,0,1,1,0,0,0,0,1.0,Middle,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,Not Parked,0,0,0,0
3,frc4467,2025,2025tnkn,2025tnkn_qm1,1,4/4/2025 12:50:00 PM,blue,frc1466,6,26,0,32,1,6,7,0,0,0,0,1.0,Processor Side,1,0,0,0,1,0,0,4,1,0,1,0,0,0,0,0,0,0,0,Not Parked,0,0,0,0
4,frc4467,2025,2025tnkn,2025tnkn_qm1,1,4/4/2025 12:50:00 PM,red,frc4630,7,8,2,17,0,2,2,1,0,1,0,1.0,Processor Side,1,0,0,0,0,0,1,0,2,0,0,0,0,0,0,0,0,0,0,Parked,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466,frc4467,2025,2025tnkn,2025tnkn_qm79,79,4/5/2025 3:46:00 PM,red,frc3324,10,42,0,52,1,11,12,0,0,0,150,1.0,Cage Side,1,1,0,0,0,0,0,4,3,2,2,0,0,0,0,0,0,150,0,Not Parked,0,0,0,0
467,frc4467,2025,2025tnkn,2025tnkn_qm79,79,4/5/2025 3:46:00 PM,red,frc3139,0,20,0,20,0,10,10,0,0,0,0,1.0,Processor Side,0,0,0,0,0,0,0,0,0,0,10,0,0,0,0,0,0,0,0,Not Parked,0,0,0,0
468,frc4467,2025,2025tnkn,2025tnkn_qm79,79,4/5/2025 3:46:00 PM,blue,frc3843,6,20,12,38,1,0,1,0,5,5,11,1.0,Middle,1,0,0,0,1,0,0,0,0,0,0,0,5,0,0,0,0,16,5,Deep Cage,0,0,0,0
469,frc4467,2025,2025tnkn,2025tnkn_qm79,79,4/5/2025 3:46:00 PM,blue,frc5002,6,12,2,20,1,3,4,0,0,0,5,1.0,Processor Side,1,0,0,0,1,0,0,0,3,0,0,0,0,0,0,0,0,5,0,Parked,0,0,0,0
470,frc4467,2025,2025tnkn,2025tnkn_qm79,79,4/5/2025 3:46:00 PM,blue,frc7072,17,30,0,47,2,6,8,0,0,0,0,0.0,Cage Side,1,2,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0

In [4]:
"""
Step 2a. Display all the data for a single column "totalTeleopPoints"
"""

scouted_data[["team_key", "totalTeleopPoints"]]

    team_key  totalTeleopPoints
0      frc21                 29
1    frc3824                 18
2    frc5045                  4
3    frc1466                 26
4    frc4630                  8
..       ...                ...
466  frc3324                 42
467  frc3139                 20
468  frc3843                 20
469  frc5002                 12
470  frc7072                 30

[471 rows x 2 columns]

In [5]:
"""
Step 2b. Display all the data for a multiple columns: "team_key", "totalTeleopPoints", "totalAUtoPoints"
"""
scouted_data[["team_key", "totalTeleopPoints"]]

    team_key  totalTeleopPoints
0      frc21                 29
1    frc3824                 18
2    frc5045                  4
3    frc1466                 26
4    frc4630                  8
..       ...                ...
466  frc3324                 42
467  frc3139                 20
468  frc3843                 20
469  frc5002                 12
470  frc7072                 30

[471 rows x 2 columns]

In [6]:
"""
Step 3a. Query for all the matches where team "frc3504" played
"""

'\nStep 3a. Query for all the matches where team "frc3504" played\n'

In [7]:
"""
Step 3b. Query for all the matches where team a team died during a match
"""

scouted_data[scouted_data["diedDuringMatch"] != 0]

,org_key,year,event_key,match_key,match_number,time,alliance,team_key,totalAutoPoints,totalTeleopPoints,totalEndgamePoints,contributedPoints,totalAutoCoral,totalTeleopCoral,totalCoral,totalAutoAlgae,totalTeleopAlgae,totalAlgae,ClimbTime,Reliability,startingPosition,didLeaveStartingZone,autoCoralL4,autoCoralL3,autoCoralL2,autoCoralL1,autoAlgaeProc,autoAlgaeNet,teleopCoralL4,teleopCoralL3,teleopCoralL2,teleopCoralL1,teleopAlgaeProc,teleopAlgaeNet,didDefense,Defenserating,totalMinorFouls,totalMajorFouls,climbingStartTime,climbingStopTime,bargeStatus,diedDuringMatch,recoveredFromFreeze,didYellowCard,didRedCard
7,frc4467,2025,2025tnkn,2025tnkn_qm2,2,4/4/2025 12:59:00 PM,red,frc4306,3,0,0,3,0,0,0,0,0,0,0,0.0,Processor Side,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
18,frc4467,2025,2025tnkn,2025tnkn_qm4,4,4/4/2025 1:17:00 PM,red,frc538,3,0,0,3,0,0,0,0,0,0,0,0.0,Processor Side,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
23,frc4467,2025,2025tnkn,2025tnkn_qm4,4,4/4/2025 1:17:00 PM,red,frc3937,0,0,0,0,0,0,0,0,0,0,0,0.0,Processor Side,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
34,frc4467,2025,2025tnkn,2025tnkn_qm6,6,4/4/2025 1:35:00 PM,red,frc6517,10,0,0,10,1,0,1,0,0,0,0,0.0,Cage Side,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
38,frc4467,2025,2025tnkn,2025tnkn_qm7,7,4/4/2025 1:44:00 PM,red,frc10101,3,10,0,13,0,2,2,0,0,0,0,0.0,Middle,1,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
45,frc4467,2025,2025tnkn,2025tnkn_qm8,8,4/4/2025 1:53:00 PM,red,frc10269,3,0,0,3,0,0,0,0,0,0,0,0.0,Cage Side,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
54,frc4467,2025,2025tnkn,2025tnkn_qm10,10,4/4/2025 2:10:00 PM,blue,frc5744,3,0,2,5,0,0,0,0,0,0,116,0.0,Processor Side,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,116,0,Parked,1,0,0,0
69,frc4467,2025,2025tnkn,2025tnkn_qm12,12,4/4/2025 2:26:00 PM,red,frc5002,3,2,0,5,0,1,1,0,0,0,0,0.0,Cage Side,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
70,frc4467,2025,2025tnkn,2025tnkn_qm12,12,4/4/2025 2:26:00 PM,blue,frc2856,3,0,0,3,0,0,0,0,0,0,0,0.0,Processor Side,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
98,frc4467,2025,2025tnkn,2025tnkn_qm17,17,4/4/2025 3:06:00 PM,red,frc7483,3,13,2,18,0,3,3,0,1,1,22,0.5,Middle,1,0,0,0,0,0,0,0,0,3,0,0,1,0,0,0,0,22,0,Parked,1,1,0,0
99,frc4467,2025,2025tnkn,2025tnkn_qm17,17,4/4/2025 3:06:00 PM,blue,frc5002,10,10,0,20,1,2,3,0,0,0,150,0.0,Processor Side,1,1,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,150,0,Not Parked,1,0,0,0
134,frc4467,2025,2025tnkn,2025tnkn_qm23,23,4/4/2025 5:00:00 PM,blue,frc4306,0,0,2,2,0,0,0,0,0,0,0,0.0,Not There,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Parked,1,0,0,0
144,frc4467,2025,2025tnkn,2025tnkn_qm25,25,4/4/2025 5:16:00 PM,red,frc2856,0,0,0,0,0,0,0,0,0,0,0,0.0,Cage Side,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
152,frc4467,2025,2025tnkn,2025tnkn_qm26,26,4/4/2025 5:24:00 PM,blue,frc1592,6,41,12,59,1,6,7,0,3,3,6,0.5,Middle,1,0,0,0,1,0,0,1,3,2,0,3,0,0,0,0,0,6,0,Deep Cage,1,1,0,0
236,frc4467,2025,2025tnkn,2025tnkn_qm40,40,4/4/2025 7:16:00 PM,red,frc3821,3,2,0,5,0,1,1,0,0,0,150,0.0,Processor Side,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,150,0,Not Parked,1,0,0,0
237,frc4467,2025,2025tnkn,2025tnkn_qm40,40,4/4/2025 7:16:00 PM,blue,frc4630,3,0,0,3,0,0,0,0,0,0,0,0.0,Processor Side,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
243,frc4467,2025,2025tnkn,2025tnkn_qm41,41,4/4/2025 7:24:00 PM,blue,frc3843,10,10,0,20,1,0,1,0,2,2,0,0.0,Middle,1,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,Not Parked,1,0,0,0
249,frc4467,2025,2025tnkn,2025tnkn_qm42,42,4/4/2025 7:32:00 PM,blue,frc4306,3,0,2,5,0,0,0,0,0,0,7,0.0,Middle,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,14,7,Parked,1,0,0,0
287,frc4467,2025,2025tnkn,2025tnkn_qm48,48,4/4/2025 8:20:00 PM,red,frc4630,3,8,0,11,0,2,2,0,0,0,0,0.0,Processor Side,1,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
337,frc4467,2025,2025tnkn,2025tnkn_qm57,57,4/4/2025 9:32:00 PM,blue,frc5744,10,0,0,10,1,0,1,0,0,0,-27,0.0,Middle,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,27,Not Parked,1,0,0,0
341,frc4467,2025,2025tnkn,2025tnkn_qm57,57,4/4/2025 9:32:00 PM,red,frc2856,3,0,0,3,0,0,0,0,0,0,0,0.0,Cage Side,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
361,frc4467,2025,2025tnkn,2025tnkn_qm61,61,4/5/2025 1:17:00 PM,blue,frc5045,9,12,0,21,1,3,4,0,0,0,150,0.5,Middle,1,0,1,0,0,0,0,0,3,0,0,0,0,0,0,0,0,150,0,Not Parked,1,1,0,0
374,frc4467,2025,2025tnkn,2025tnkn_qm63,63,4/5/2025 1:35:00 PM,blue,frc10101,3,0,0,3,0,0,0,0,0,0,150,0.0,Middle,1,0,0,0,0,0,0,0,0,0,0,0,0,0,7,0,0,150,0,Not Parked,1,0,0,0
383,frc4467,2025,2025tnkn,2025tnkn_qm64,64,4/5/2025 1:44:00 PM,red,frc2856,0,2,0,2,0,1,1,0,0,0,150,0.0,Middle,0,0,0,0,0,0,0,0,0,0,1,0,0,1,2,0,0,150,0,Not Parked,1,0,0,0
394,frc4467,2025,2025tnkn,2025tnkn_qm66,66,4/5/2025 2:02:00 PM,red,frc4630,0,4,0,4,0,1,1,0,0,0,0,0.5,Not There,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,Not Parked,1,1,0,0
398,frc4467,2025,2025tnkn,2025tnkn_qm67,67,4/5/2025 2:10:00 PM,red,frc3492,3,19,0,22,0,6,6,0,0,0,0,0.0,Middle,1,0,0,0,0,0,0,0,2,3,1,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
442,frc4467,2025,2025tnkn,2025tnkn_qm75,75,4/5/2025 3:14:00 PM,red,frc10137,3,0,2,5,0,0,0,0,0,0,3,0.5,Processor Side,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,Parked,1,1,0,0
446,frc4467,2025,2025tnkn,2025tnkn_qm75,75,4/5/2025 3:14:00 PM,red,frc2856,3,0,0,3,0,0,0,0,0,0,150,0.0,Middle,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,150,0,Not Parked,1,0,0,0
457,frc4467,2025,2025tnkn,2025tnkn_qm77,77,4/5/2025 3:30:00 PM,blue,frc5045,9,8,0,17,1,2,3,0,0,0,0,0.0,Middle,1,0,1,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
460,frc4467,2025,2025tnkn,2025tnkn_qm78,78,4/5/2025 3:38:00 PM,blue,frc9152,3,0,0,3,0,0,0,0,0,0,0,0.0,Processor Side,1,0,0,0,0,0,0,0,0,0,0,0,0,1,5,0,0,0,0,Not Parked,1,0,0,0
470,frc4467,2025,2025tnkn,2025tnkn_qm79,79,4/5/2025 3:46:00 PM,blue,frc7072,17,30,0,47,2,6,8,0,0,0,0,0.0,Cage Side,1,2,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0

In [8]:
"""
Step 3b. Query for all the instances when a team scored more than 8 pieces of coral
"""

'\nStep 3b. Query for all the instances when a team scored more than 8 pieces of coral\n'

In [9]:
"""
Step XXXX. Calculate the averages stats per team and display them
"""

'\nStep XXXX. Calculate the averages stats per team and display them\n'

In [10]:
"""
Step XXXX. Filter teams that scored an average of more than 2 pieces of algae
"""

'\nStep XXXX. Filter teams that scored an average of more than 2 pieces of algae\n'

In [11]:
"""
Step XXXX. Query for ALL the scouted data for the teams listed in the array
"""

teams_in_match = ["frc21", "frc3824", "frc5045", "frc1466", "frc4630", "frc5744"]

In [12]:
"""
Step XXXX. Query for the average scouted data for the teams listed in the array
"""

teams_in_match = ["frc21", "frc3824", "frc5045", "frc1466", "frc4630", "frc5744"]

In [13]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Sam', 'Charlie', 'Tom', 'Bob'],
    'Age': [25, 30, 35, 30, 42, 21],
    'City': ['New York', 'London', 'Paris', 'Pittsburgh', "Rochester", "Seattle"]
})
df

# df["Favorite Color"] = ["Red", "Green", "Blue", "Pink", "Yellow", "Orange"]

# # Or using existing data
# df["Dog Years"] = df["Age"] / 7.0

# df.sum()

df.groupby("Name").median(numeric_only=True)

          Age
Name
Alice    25.0
Bob      25.5
Charlie  30.0
Sam      35.0
Tom      42.0