In [29]:
"""
This cell imports all the necessary 3rd party libraries and loads our scouted matches
"""

import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

scouted_data = df = pd.read_csv("data/scouted_data.csv")

In [30]:
"""
Step 1.

"print" the scouted data dataframe. You can either explicitly print() it, or just have it be the last item in the cell
"""
scouted_data

     org_key  year event_key      match_key  match_number  \
0    frc4467  2025  2025tnkn   2025tnkn_qm1             1
1    frc4467  2025  2025tnkn   2025tnkn_qm1             1
2    frc4467  2025  2025tnkn   2025tnkn_qm1             1
3    frc4467  2025  2025tnkn   2025tnkn_qm1             1
4    frc4467  2025  2025tnkn   2025tnkn_qm1             1
5    frc4467  2025  2025tnkn   2025tnkn_qm1             1
6    frc4467  2025  2025tnkn   2025tnkn_qm2             2
7    frc4467  2025  2025tnkn   2025tnkn_qm2             2
8    frc4467  2025  2025tnkn   2025tnkn_qm2             2
9    frc4467  2025  2025tnkn   2025tnkn_qm2             2
10   frc4467  2025  2025tnkn   2025tnkn_qm2             2
11   frc4467  2025  2025tnkn   2025tnkn_qm2             2
12   frc4467  2025  2025tnkn   2025tnkn_qm3             3
13   frc4467  2025  2025tnkn   2025tnkn_qm3             3
14   frc4467  2025  2025tnkn   2025tnkn_qm3             3
15   frc4467  2025  2025tnkn   2025tnkn_qm3             3
16   frc4467  2025  2025tnkn   2025tnkn_qm3             3
17   frc4467  2025  2025tnkn   2025tnkn_qm3             3
18   frc4467  2025  2025tnkn   2025tnkn_qm4             4
19   frc4467  2025  2025tnkn   2025tnkn_qm4             4
20   frc4467  2025  2025tnkn   2025tnkn_qm4             4
21   frc4467  2025  2025tnkn   2025tnkn_qm4             4
22   frc4467  2025  2025tnkn   2025tnkn_qm4             4
23   frc4467  2025  2025tnkn   2025tnkn_qm4             4
24   frc4467  2025  2025tnkn   2025tnkn_qm5             5
25   frc4467  2025  2025tnkn   2025tnkn_qm5             5
26   frc4467  2025  2025tnkn   2025tnkn_qm5             5
27   frc4467  2025  2025tnkn   2025tnkn_qm5             5
28   frc4467  2025  2025tnkn   2025tnkn_qm5             5
29   frc4467  2025  2025tnkn   2025tnkn_qm5             5
30   frc4467  2025  2025tnkn   2025tnkn_qm6             6
31   frc4467  2025  2025tnkn   2025tnkn_qm6             6
32   frc4467  2025  2025tnkn   2025tnkn_qm6             6
33   frc4467  2025  2025tnkn   2025tnkn_qm6             6
34   frc4467  2025  2025tnkn   2025tnkn_qm6             6
35   frc4467  2025  2025tnkn   2025tnkn_qm6             6
36   frc4467  2025  2025tnkn   2025tnkn_qm7             7
37   frc4467  2025  2025tnkn   2025tnkn_qm7             7
38   frc4467  2025  2025tnkn   2025tnkn_qm7             7
39   frc4467  2025  2025tnkn   2025tnkn_qm7             7
40   frc4467  2025  2025tnkn   2025tnkn_qm7             7
41   frc4467  2025  2025tnkn   2025tnkn_qm7             7
42   frc4467  2025  2025tnkn   2025tnkn_qm8             8
43   frc4467  2025  2025tnkn   2025tnkn_qm8             8
44   frc4467  2025  2025tnkn   2025tnkn_qm8             8
45   frc4467  2025  2025tnkn   2025tnkn_qm8             8
46   frc4467  2025  2025tnkn   2025tnkn_qm8             8
47   frc4467  2025  2025tnkn   2025tnkn_qm8             8
48   frc4467  2025  2025tnkn   2025tnkn_qm9             9
49   frc4467  2025  2025tnkn   2025tnkn_qm9             9
50   frc4467  2025  2025tnkn   2025tnkn_qm9             9
51   frc4467  2025  2025tnkn   2025tnkn_qm9             9
52   frc4467  2025  2025tnkn   2025tnkn_qm9             9
53   frc4467  2025  2025tnkn   2025tnkn_qm9             9
54   frc4467  2025  2025tnkn  2025tnkn_qm10            10
55   frc4467  2025  2025tnkn  2025tnkn_qm10            10
56   frc4467  2025  2025tnkn  2025tnkn_qm10            10
57   frc4467  2025  2025tnkn  2025tnkn_qm10            10
58   frc4467  2025  2025tnkn  2025tnkn_qm10            10
59   frc4467  2025  2025tnkn  2025tnkn_qm10            10
60   frc4467  2025  2025tnkn  2025tnkn_qm11            11
61   frc4467  2025  2025tnkn  2025tnkn_qm11            11
62   frc4467  2025  2025tnkn  2025tnkn_qm11            11
63   frc4467  2025  2025tnkn  2025tnkn_qm11            11
64   frc4467  2025  2025tnkn  2025tnkn_qm11            11
65   frc4467  2025  2025tnkn  2025tnkn_qm11            11
66   frc4467  2025  2025tnkn  2025tnkn_qm12            12
67   frc4467  2025  2025tnkn  2025tnkn_qm12            12
68   frc4467  2025  2025tnkn  2025tnkn_qm12            12
69   frc4467  2025  2025tnkn  2025tnkn_qm12            12
70   frc4467  2025  2025tnkn  2025tnkn_qm12            12
71   frc4467  2025  2025tnkn  2025tnkn_qm12            12
72   frc4467  2025  2025tnkn  2025tnkn_qm13            13
73   frc4467  2025  2025tnkn  2025tnkn_qm13            13
74   frc4467  2025  2025tnkn  2025tnkn_qm13            13
75   frc4467  2025  2025tnkn  2025tnkn_qm13            13
76   frc4467  2025  2025tnkn  2025tnkn_qm13            13
77   frc4467  2025  2025tnkn  2025tnkn_qm13            13
78   frc4467  2025  2025tnkn  2025tnkn_qm14            14
79   frc4467  2025  2025tnkn  2025tnkn_qm14            14
80   frc4467  2025  2025tnkn  2025tnkn_qm14            14
81   frc4467  2025  2025tnkn  2025tnkn_qm14            14
82   frc4467  2025  2025tnkn  2025tnkn_qm14            14
83   frc4467  2025  2025tnkn  2025tnkn_qm14            14
84   frc4467  2025  2025tnkn  2025tnkn_qm15            15
85   frc4467  2025  2025tnkn  2025tnkn_qm15            15
86   frc4467  2025  2025tnkn  2025tnkn_qm15            15
87   frc4467  2025  2025tnkn  2025tnkn_qm15            15
88   frc4467  2025  2025tnkn  2025tnkn_qm15            15
89   frc4467  2025  2025tnkn  2025tnkn_qm15            15
90   frc4467  2025  2025tnkn  2025tnkn_qm16            16
91   frc4467  2025  2025tnkn  2025tnkn_qm16            16
92   frc4467  2025  2025tnkn  2025tnkn_qm16            16
93   frc4467  2025  2025tnkn  2025tnkn_qm16            16
94   frc4467  2025  2025tnkn  2025tnkn_qm16            16
95   frc4467  2025  2025tnkn  2025tnkn_qm16            16
96   frc4467  2025  2025tnkn  2025tnkn_qm17            17
97   frc4467  2025  2025tnkn  2025tnkn_qm17            17
98   frc4467  2025  2025tnkn  2025tnkn_qm17            17
99   frc4467  2025  2025tnkn  2025tnkn_qm17            17
100  frc4467  2025  2025tnkn  2025tnkn_qm17            17
101  frc4467  2025  2025tnkn  2025tnkn_qm17            17
102  frc4467  2025  2025tnkn  2025tnkn_qm18            18
103  frc4467  2025  2025tnkn  2025tnkn_qm18            18
104  frc4467  2025  2025tnkn  2025tnkn_qm18            18
105  frc4467  2025  2025tnkn  2025tnkn_qm18            18
106  frc4467  2025  2025tnkn  2025tnkn_qm18            18
107  frc4467  2025  2025tnkn  2025tnkn_qm18            18
108  frc4467  2025  2025tnkn  2025tnkn_qm19            19
109  frc4467  2025  2025tnkn  2025tnkn_qm19            19
110  frc4467  2025  2025tnkn  2025tnkn_qm19            19
111  frc4467  2025  2025tnkn  2025tnkn_qm19            19
112  frc4467  2025  2025tnkn  2025tnkn_qm19            19
113  frc4467  2025  2025tnkn  2025tnkn_qm19            19
114  frc4467  2025  2025tnkn  2025tnkn_qm20            20
115  frc4467  2025  2025tnkn  2025tnkn_qm20            20
116  frc4467  2025  2025tnkn  2025tnkn_qm20            20
117  frc4467  2025  2025tnkn  2025tnkn_qm20            20
118  frc4467  2025  2025tnkn  2025tnkn_qm20            20
119  frc4467  2025  2025tnkn  2025tnkn_qm20            20
120  frc4467  2025  2025tnkn  2025tnkn_qm21            21
121  frc4467  2025  2025tnkn  2025tnkn_qm21            21
122  frc4467  2025  2025tnkn  2025tnkn_qm21            21
123  frc4467  2025  2025tnkn  2025tnkn_qm21            21
124  frc4467  2025  2025tnkn  2025tnkn_qm21            21
125  frc4467  2025  2025tnkn  2025tnkn_qm21            21
126  frc4467  2025  2025tnkn  2025tnkn_qm22            22
127  frc4467  2025  2025tnkn  2025tnkn_qm22            22
128  frc4467  2025  2025tnkn  2025tnkn_qm22            22
129  frc4467  2025  2025tnkn  2025tnkn_qm22            22
130  frc4467  2025  2025tnkn  2025tnkn_qm22            22
131  frc4467  2025  2025tnkn  2025tnkn_qm22            22
132  frc4467  2025  2025tnkn  2025tnkn_qm23            23
133  frc4467  2025  2025tnkn  2025tnkn_qm23            23
134  frc4467  2025  2025tnkn  2025tnkn_qm23            23
135  frc4467  2025  2025tnkn  2025tnkn_qm23            23
136  frc4467  2025  2025tnkn  2025tnkn_qm23            23
137  frc4467  2025  2025tnkn  2025tnkn_qm23            23
138  frc4467  2025  2025tnkn  2025tnkn_qm24            24
139  frc4467  2025  2025tnkn  2025tnkn_qm24            24
140  frc4467  2025  2025tnkn  2025tnkn_qm24            24
141  frc4467  2025  2025tnkn  2025tnkn_qm24            24
142  frc4467  2025  2025tnkn  2025tnkn_qm24            24
143  frc4467  2025  2025tnkn  2025tnkn_qm24            24
144  frc4467  2025  2025tnkn  2025tnkn_qm25            25
145  frc4467  2025  2025tnkn  2025tnkn_qm25            25
146  frc4467  2025  2025tnkn  2025tnkn_qm25            25
147  frc4467  2025  2025tnkn  2025tnkn_qm25            25
148  frc4467  2025  2025tnkn  2025tnkn_qm25            25
149  frc4467  2025  2025tnkn  2025tnkn_qm25            25
150  frc4467  2025  2025tnkn  2025tnkn_qm26            26
151  frc4467  2025  2025tnkn  2025tnkn_qm26            26
152  frc4467  2025  2025tnkn  2025tnkn_qm26            26
153  frc4467  2025  2025tnkn  2025tnkn_qm26            26
154  frc4467  2025  2025tnkn  2025tnkn_qm26            26
155  frc4467  2025  2025tnkn  2025tnkn_qm26            26
156  frc4467  2025  2025tnkn  2025tnkn_qm27            27
157  frc4467  2025  2025tnkn  2025tnkn_qm27            27
158  frc4467  2025  2025tnkn  2025tnkn_qm27            27
159  frc4467  2025  2025tnkn  2025tnkn_qm27            27
160  frc4467  2025  2025tnkn  2025tnkn_qm27            27
161  frc4467  2025  2025tnkn  2025tnkn_qm27            27
162  frc4467  2025  2025tnkn  2025tnkn_qm28            28
163  frc4467  2025  2025tnkn  2025tnkn_qm28            28
164  frc4467  2025  2025tnkn  2025tnkn_qm28            28
165  frc4467  2025  2025tnkn  2025tnkn_qm28            28
166  frc4467  2025  2025tnkn  2025tnkn_qm28            28
167  frc4467  2025  2025tnkn  2025tnkn_qm28            28
168  frc4467  2025  2025tnkn  2025tnkn_qm29            29
169  frc4467  2025  2025tnkn  2025tnkn_qm29            29
170  frc4467  2025  2025tnkn  2025tnkn_qm29            29
171  frc4467  2025  2025tnkn  2025tnkn_qm29            29
172  frc4467  2025  2025tnkn  2025tnkn_qm29            29
173  frc4467  2025  2025tnkn  2025tnkn_qm29            29
174  frc4467  2025  2025tnkn  2025tnkn_qm30            30
175  frc4467  2025  2025tnkn  2025tnkn_qm30            30
176  frc4467  2025  2025tnkn  2025tnkn_qm30            30
177  frc4467  2025  2025tnkn  2025tnkn_qm30            30
178  frc4467  2025  2025tnkn  2025tnkn_qm30            30
179  frc4467  2025  2025tnkn  2025tnkn_qm30            30
180  frc4467  2025  2025tnkn  2025tnkn_qm31            31
181  frc4467  2025  2025tnkn  2025tnkn_qm31            31
182  frc4467  2025  2025tnkn  2025tnkn_qm31            31
183  frc4467  2025  2025tnkn  2025tnkn_qm31            31
184  frc4467  2025  2025tnkn  2025tnkn_qm31            31
185  frc4467  2025  2025tnkn  2025tnkn_qm31            31
186  frc4467  2025  2025tnkn  2025tnkn_qm32            32
187  frc4467  2025  2025tnkn  2025tnkn_qm32            32
188  frc4467  2025  2025tnkn  2025tnkn_qm32            32
189  frc4467  2025  2025tnkn  2025tnkn_qm32            32
190  frc4467  2025  2025tnkn  2025tnkn_qm32            32
191  frc4467  2025  2025tnkn  2025tnkn_qm32            32
192  frc4467  2025  2025tnkn  2025tnkn_qm33            33
193  frc4467  2025  2025tnkn  2025tnkn_qm33            33
194  frc4467  2025  2025tnkn  2025tnkn_qm33            33
195  frc4467  2025  2025tnkn  2025tnkn_qm33            33
196  frc4467  2025  2025tnkn  2025tnkn_qm33            33
197  frc4467  2025  2025tnkn  2025tnkn_qm33            33
198  frc4467  2025  2025tnkn  2025tnkn_qm34            34
199  frc4467  2025  2025tnkn  2025tnkn_qm34            34
200  frc4467  2025  2025tnkn  2025tnkn_qm34            34
201  frc4467  2025  2025tnkn  2025tnkn_qm34            34
202  frc4467  2025  2025tnkn  2025tnkn_qm34            34
203  frc4467  2025  2025tnkn  2025tnkn_qm34            34
204  frc4467  2025  2025tnkn  2025tnkn_qm35            35
205  frc4467  2025  2025tnkn  2025tnkn_qm35            35
206  frc4467  2025  2025tnkn  2025tnkn_qm35            35
207  frc4467  2025  2025tnkn  2025tnkn_qm35            35
208  frc4467  2025  2025tnkn  2025tnkn_qm35            35
209  frc4467  2025  2025tnkn  2025tnkn_qm35            35
210  frc4467  2025  2025tnkn  2025tnkn_qm36            36
211  frc4467  2025  2025tnkn  2025tnkn_qm36            36
212  frc4467  2025  2025tnkn  2025tnkn_qm36            36
213  frc4467  2025  2025tnkn  2025tnkn_qm36            36
214  frc4467  2025  2025tnkn  2025tnkn_qm36            36
215  frc4467  2025  2025tnkn  2025tnkn_qm36            36
216  frc4467  2025  2025tnkn  2025tnkn_qm37            37
217  frc4467  2025  2025tnkn  2025tnkn_qm37            37
218  frc4467  2025  2025tnkn  2025tnkn_qm37            37
219  frc4467  2025  2025tnkn  2025tnkn_qm37            37
220  frc4467  2025  2025tnkn  2025tnkn_qm37            37
221  frc4467  2025  2025tnkn  2025tnkn_qm37            37
222  frc4467  2025  2025tnkn  2025tnkn_qm38            38
223  frc4467  2025  2025tnkn  2025tnkn_qm38            38
224  frc4467  2025  2025tnkn  2025tnkn_qm38            38
225  frc4467  2025  2025tnkn  2025tnkn_qm38            38
226  frc4467  2025  2025tnkn  2025tnkn_qm38            38
227  frc4467  2025  2025tnkn  2025tnkn_qm38            38
228  frc4467  2025  2025tnkn  2025tnkn_qm39            39
229  frc4467  2025  2025tnkn  2025tnkn_qm39            39
230  frc4467  2025  2025tnkn  2025tnkn_qm39            39
231  frc4467  2025  2025tnkn  2025tnkn_qm39            39
232  frc4467  2025  2025tnkn  2025tnkn_qm39            39
233  frc4467  2025  2025tnkn  2025tnkn_qm39            39
234  frc4467  2025  2025tnkn  2025tnkn_qm40            40
235  frc4467  2025  2025tnkn  2025tnkn_qm40            40
236  frc4467  2025  2025tnkn  2025tnkn_qm40            40
237  frc4467  2025  2025tnkn  2025tnkn_qm40            40
238  frc4467  2025  2025tnkn  2025tnkn_qm40            40
239  frc4467  2025  2025tnkn  2025tnkn_qm40            40
240  frc4467  2025  2025tnkn  2025tnkn_qm41            41
241  frc4467  2025  2025tnkn  2025tnkn_qm41            41
242  frc4467  2025  2025tnkn  2025tnkn_qm41            41
243  frc4467  2025  2025tnkn  2025tnkn_qm41            41
244  frc4467  2025  2025tnkn  2025tnkn_qm41            41
245  frc4467  2025  2025tnkn  2025tnkn_qm41            41
246  frc4467  2025  2025tnkn  2025tnkn_qm42            42
247  frc4467  2025  2025tnkn  2025tnkn_qm42            42
248  frc4467  2025  2025tnkn  2025tnkn_qm42            42
249  frc4467  2025  2025tnkn  2025tnkn_qm42            42
250  frc4467  2025  2025tnkn  2025tnkn_qm42            42
251  frc4467  2025  2025tnkn  2025tnkn_qm42            42
252  frc4467  2025  2025tnkn  2025tnkn_qm43            43
253  frc4467  2025  2025tnkn  2025tnkn_qm43            43
254  frc4467  2025  2025tnkn  2025tnkn_qm43            43
255  frc4467  2025  2025tnkn  2025tnkn_qm43            43
256  frc4467  2025  2025tnkn  2025tnkn_qm43            43
257  frc4467  2025  2025tnkn  2025tnkn_qm43            43
258  frc4467  2025  2025tnkn  2025tnkn_qm44            44
259  frc4467  2025  2025tnkn  2025tnkn_qm44            44
260  frc4467  2025  2025tnkn  2025tnkn_qm44            44
261  frc4467  2025  2025tnkn  2025tnkn_qm44            44
262  frc4467  2025  2025tnkn  2025tnkn_qm44            44
263  frc4467  2025  2025tnkn  2025tnkn_qm44            44
264  frc4467  2025  2025tnkn  2025tnkn_qm45            45
265  frc4467  2025  2025tnkn  2025tnkn_qm45            45
266  frc4467  2025  2025tnkn  2025tnkn_qm45            45
267  frc4467  2025  2025tnkn  2025tnkn_qm45            45
268  frc4467  2025  2025tnkn  2025tnkn_qm45            45
269  frc4467  2025  2025tnkn  2025tnkn_qm45            45
270  frc4467  2025  2025tnkn  2025tnkn_qm46            46
271  frc4467  2025  2025tnkn  2025tnkn_qm46            46
272  frc4467  2025  2025tnkn  2025tnkn_qm46            46
273  frc4467  2025  2025tnkn  2025tnkn_qm46            46
274  frc4467  2025  2025tnkn  2025tnkn_qm46            46
275  frc4467  2025  2025tnkn  2025tnkn_qm46            46
276  frc4467  2025  2025tnkn  2025tnkn_qm47            47
277  frc4467  2025  2025tnkn  2025tnkn_qm47            47
278  frc4467  2025  2025tnkn  2025tnkn_qm47            47
279  frc4467  2025  2025tnkn  2025tnkn_qm47            47
280  frc4467  2025  2025tnkn  2025tnkn_qm47            47
281  frc4467  2025  2025tnkn  2025tnkn_qm47            47
282  frc4467  2025  2025tnkn  2025tnkn_qm48            48
283  frc4467  2025  2025tnkn  2025tnkn_qm48            48
284  frc4467  2025  2025tnkn  2025tnkn_qm48            48
285  frc4467  2025  2025tnkn  2025tnkn_qm48            48
286  frc4467  2025  2025tnkn  2025tnkn_qm48            48
287  frc4467  2025  2025tnkn  2025tnkn_qm48            48
288  frc4467  2025  2025tnkn  2025tnkn_qm49            49
289  frc4467  2025  2025tnkn  2025tnkn_qm49            49
290  frc4467  2025  2025tnkn  2025tnkn_qm49            49
291  frc4467  2025  2025tnkn  2025tnkn_qm49            49
292  frc4467  2025  2025tnkn  2025tnkn_qm49            49
293  frc4467  2025  2025tnkn  2025tnkn_qm49            49
294  frc4467  2025  2025tnkn  2025tnkn_qm50            50
295  frc4467  2025  2025tnkn  2025tnkn_qm50            50
296  frc4467  2025  2025tnkn  2025tnkn_qm50            50
297  frc4467  2025  2025tnkn  2025tnkn_qm50            50
298  frc4467  2025  2025tnkn  2025tnkn_qm50            50
299  frc4467  2025  2025tnkn  2025tnkn_qm50            50
300  frc4467  2025  2025tnkn  2025tnkn_qm51            51
301  frc4467  2025  2025tnkn  2025tnkn_qm51            51
302  frc4467  2025  2025tnkn  2025tnkn_qm51            51
303  frc4467  2025  2025tnkn  2025tnkn_qm51            51
304  frc4467  2025  2025tnkn  2025tnkn_qm51            51
305  frc4467  2025  2025tnkn  2025tnkn_qm51            51
306  frc4467  2025  2025tnkn  2025tnkn_qm52            52
307  frc4467  2025  2025tnkn  2025tnkn_qm52            52
308  frc4467  2025  2025tnkn  2025tnkn_qm52            52
309  frc4467  2025  2025tnkn  2025tnkn_qm52            52
310  frc4467  2025  2025tnkn  2025tnkn_qm52            52
311  frc4467  2025  2025tnkn  2025tnkn_qm52            52
312  frc4467  2025  2025tnkn  2025tnkn_qm53            53
313  frc4467  2025  2025tnkn  2025tnkn_qm53            53
314  frc4467  2025  2025tnkn  2025tnkn_qm53            53
315  frc4467  2025  2025tnkn  2025tnkn_qm53            53
316  frc4467  2025  2025tnkn  2025tnkn_qm53            53
317  frc4467  2025  2025tnkn  2025tnkn_qm53            53
318  frc4467  2025  2025tnkn  2025tnkn_qm54            54
319  frc4467  2025  2025tnkn  2025tnkn_qm54            54
320  frc4467  2025  2025tnkn  2025tnkn_qm54            54
321  frc4467  2025  2025tnkn  2025tnkn_qm54            54
322  frc4467  2025  2025tnkn  2025tnkn_qm54            54
323  frc4467  2025  2025tnkn  2025tnkn_qm54            54
324  frc4467  2025  2025tnkn  2025tnkn_qm55            55
325  frc4467  2025  2025tnkn  2025tnkn_qm55            55
326  frc4467  2025  2025tnkn  2025tnkn_qm55            55
327  frc4467  2025  2025tnkn  2025tnkn_qm55            55
328  frc4467  2025  2025tnkn  2025tnkn_qm55            55
329  frc4467  2025  2025tnkn  2025tnkn_qm55            55
330  frc4467  2025  2025tnkn  2025tnkn_qm56            56
331  frc4467  2025  2025tnkn  2025tnkn_qm56            56
332  frc4467  2025  2025tnkn  2025tnkn_qm56            56
333  frc4467  2025  2025tnkn  2025tnkn_qm56            56
334  frc4467  2025  2025tnkn  2025tnkn_qm56            56
335  frc4467  2025  2025tnkn  2025tnkn_qm56            56
336  frc4467  2025  2025tnkn  2025tnkn_qm57            57
337  frc4467  2025  2025tnkn  2025tnkn_qm57            57
338  frc4467  2025  2025tnkn  2025tnkn_qm57            57
339  frc4467  2025  2025tnkn  2025tnkn_qm57            57
340  frc4467  2025  2025tnkn  2025tnkn_qm57            57
341  frc4467  2025  2025tnkn  2025tnkn_qm57            57
342  frc4467  2025  2025tnkn  2025tnkn_qm58            58

In [21]:
"""
Step 2a. Display all the data for a single column "totalTeleopPoints"
"""
scouted_data["totalTeleopPoints"]

0      29
1      18
       ..
469    12
470    30
Name: totalTeleopPoints, Length: 471, dtype: int64

In [24]:
"""
Step 2b. Display all the data for a multiple columns: "team_key", "totalTeleopPoints", "totalAUtoPoints"
"""
scouted_data[["team_key", "totalTeleopPoints", "totalAutoPoints"]]

    team_key  totalTeleopPoints  totalAutoPoints
0      frc21                 29               10
1    frc3824                 18                6
..       ...                ...              ...
469  frc5002                 12                6
470  frc7072                 30               17

[471 rows x 3 columns]

In [31]:
"""
Step 3a. Query for all the matches where team "frc3504" played
"""
scouted_data[scouted_data["team_key"]=="frc3504"]

,org_key,year,event_key,match_key,match_number,time,alliance,team_key,totalAutoPoints,totalTeleopPoints,totalEndgamePoints,contributedPoints,totalAutoCoral,totalTeleopCoral,totalCoral,totalAutoAlgae,totalTeleopAlgae,totalAlgae,ClimbTime,Reliability,startingPosition,didLeaveStartingZone,autoCoralL4,autoCoralL3,autoCoralL2,autoCoralL1,autoAlgaeProc,autoAlgaeNet,teleopCoralL4,teleopCoralL3,teleopCoralL2,teleopCoralL1,teleopAlgaeProc,teleopAlgaeNet,didDefense,Defenserating,totalMinorFouls,totalMajorFouls,climbingStartTime,climbingStopTime,bargeStatus,diedDuringMatch,recoveredFromFreeze,didYellowCard,didRedCard
9,frc4467,2025,2025tnkn,2025tnkn_qm2,2,4/4/2025 12:59:00 PM,blue,frc3504,13,13,2,28,1,4,5,1,0,1,0,1.0,Not There,0,1,0,0,0,1,0,1,1,0,2,0,0,0,0,0,0,0,0,Parked,0,0,0,0
81,frc4467,2025,2025tnkn,2025tnkn_qm14,14,4/4/2025 2:42:00 PM,blue,frc3504,17,27,2,46,2,7,9,0,0,0,4,1.0,Processor Side,1,2,0,0,0,0,0,3,1,2,1,0,0,0,0,0,0,4,0,Parked,0,0,0,0
111,frc4467,2025,2025tnkn,2025tnkn_qm19,19,4/4/2025 3:22:00 PM,blue,frc3504,17,23,2,42,2,5,7,0,0,0,5,1.0,Processor Side,1,2,0,0,0,0,0,3,2,0,0,0,0,0,0,0,0,10,5,Parked,0,0,0,0
173,frc4467,2025,2025tnkn,2025tnkn_qm29,29,4/4/2025 5:48:00 PM,red,frc3504,17,27,2,46,2,7,9,0,0,0,4,1.0,Cage Side,1,2,0,0,0,0,0,2,3,1,1,0,0,0,0,0,0,4,0,Parked,0,0,0,0
200,frc4467,2025,2025tnkn,2025tnkn_qm34,34,4/4/2025 6:28:00 PM,blue,frc3504,17,30,2,49,2,7,9,0,0,0,0,1.0,Processor Side,1,2,0,0,0,0,0,3,3,1,0,0,0,0,0,0,0,0,0,Parked,0,0,0,0
244,frc4467,2025,2025tnkn,2025tnkn_qm41,41,4/4/2025 7:24:00 PM,red,frc3504,17,35,2,54,2,7,9,0,0,0,0,1.0,Processor Side,1,2,0,0,0,0,0,7,0,0,0,0,0,0,0,0,0,0,0,Parked,0,0,0,0
289,frc4467,2025,2025tnkn,2025tnkn_qm49,49,4/4/2025 8:28:00 PM,red,frc3504,14,28,0,42,2,6,8,0,0,0,0,1.0,Processor Side,0,2,0,0,0,0,0,4,2,0,0,0,0,0,0,0,0,0,0,Not Parked,0,0,0,0
370,frc4467,2025,2025tnkn,2025tnkn_qm62,62,4/5/2025 1:26:00 PM,blue,frc3504,17,25,2,44,2,5,7,0,0,0,0,1.0,Cage Side,1,2,0,0,0,0,0,5,0,0,0,0,0,0,0,0,0,0,0,Parked,0,0,0,0
419,frc4467,2025,2025tnkn,2025tnkn_qm71,71,4/5/2025 2:42:00 PM,red,frc3504,10,37,2,49,1,8,9,0,0,0,3,1.0,Cage Side,1,1,0,0,0,0,0,5,3,0,0,0,0,0,0,0,0,3,0,Parked,0,0,0,0
448,frc4467,2025,2025tnkn,2025tnkn_qm76,76,4/5/2025 3:22:00 PM,red,frc3504,17,19,2,38,2,4,6,0,0,0,-3,1.0,Processor Side,1,2,0,0,0,0,0,3,1,0,0,0,0,0,0,0,0,0,3,Parked,0,0,0,0

In [34]:
"""
Step 3b. Query for all the matches where team a team died during a match
"""
scouted_data[scouted_data["diedDuringMatch"]==1]

,org_key,year,event_key,match_key,match_number,time,alliance,team_key,totalAutoPoints,totalTeleopPoints,totalEndgamePoints,contributedPoints,totalAutoCoral,totalTeleopCoral,totalCoral,totalAutoAlgae,totalTeleopAlgae,totalAlgae,ClimbTime,Reliability,startingPosition,didLeaveStartingZone,autoCoralL4,autoCoralL3,autoCoralL2,autoCoralL1,autoAlgaeProc,autoAlgaeNet,teleopCoralL4,teleopCoralL3,teleopCoralL2,teleopCoralL1,teleopAlgaeProc,teleopAlgaeNet,didDefense,Defenserating,totalMinorFouls,totalMajorFouls,climbingStartTime,climbingStopTime,bargeStatus,diedDuringMatch,recoveredFromFreeze,didYellowCard,didRedCard
7,frc4467,2025,2025tnkn,2025tnkn_qm2,2,4/4/2025 12:59:00 PM,red,frc4306,3,0,0,3,0,0,0,0,0,0,0,0.0,Processor Side,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
18,frc4467,2025,2025tnkn,2025tnkn_qm4,4,4/4/2025 1:17:00 PM,red,frc538,3,0,0,3,0,0,0,0,0,0,0,0.0,Processor Side,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
23,frc4467,2025,2025tnkn,2025tnkn_qm4,4,4/4/2025 1:17:00 PM,red,frc3937,0,0,0,0,0,0,0,0,0,0,0,0.0,Processor Side,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
34,frc4467,2025,2025tnkn,2025tnkn_qm6,6,4/4/2025 1:35:00 PM,red,frc6517,10,0,0,10,1,0,1,0,0,0,0,0.0,Cage Side,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
38,frc4467,2025,2025tnkn,2025tnkn_qm7,7,4/4/2025 1:44:00 PM,red,frc10101,3,10,0,13,0,2,2,0,0,0,0,0.0,Middle,1,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
45,frc4467,2025,2025tnkn,2025tnkn_qm8,8,4/4/2025 1:53:00 PM,red,frc10269,3,0,0,3,0,0,0,0,0,0,0,0.0,Cage Side,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
54,frc4467,2025,2025tnkn,2025tnkn_qm10,10,4/4/2025 2:10:00 PM,blue,frc5744,3,0,2,5,0,0,0,0,0,0,116,0.0,Processor Side,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,116,0,Parked,1,0,0,0
69,frc4467,2025,2025tnkn,2025tnkn_qm12,12,4/4/2025 2:26:00 PM,red,frc5002,3,2,0,5,0,1,1,0,0,0,0,0.0,Cage Side,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
70,frc4467,2025,2025tnkn,2025tnkn_qm12,12,4/4/2025 2:26:00 PM,blue,frc2856,3,0,0,3,0,0,0,0,0,0,0,0.0,Processor Side,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
98,frc4467,2025,2025tnkn,2025tnkn_qm17,17,4/4/2025 3:06:00 PM,red,frc7483,3,13,2,18,0,3,3,0,1,1,22,0.5,Middle,1,0,0,0,0,0,0,0,0,3,0,0,1,0,0,0,0,22,0,Parked,1,1,0,0
99,frc4467,2025,2025tnkn,2025tnkn_qm17,17,4/4/2025 3:06:00 PM,blue,frc5002,10,10,0,20,1,2,3,0,0,0,150,0.0,Processor Side,1,1,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,150,0,Not Parked,1,0,0,0
134,frc4467,2025,2025tnkn,2025tnkn_qm23,23,4/4/2025 5:00:00 PM,blue,frc4306,0,0,2,2,0,0,0,0,0,0,0,0.0,Not There,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Parked,1,0,0,0
144,frc4467,2025,2025tnkn,2025tnkn_qm25,25,4/4/2025 5:16:00 PM,red,frc2856,0,0,0,0,0,0,0,0,0,0,0,0.0,Cage Side,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
152,frc4467,2025,2025tnkn,2025tnkn_qm26,26,4/4/2025 5:24:00 PM,blue,frc1592,6,41,12,59,1,6,7,0,3,3,6,0.5,Middle,1,0,0,0,1,0,0,1,3,2,0,3,0,0,0,0,0,6,0,Deep Cage,1,1,0,0
236,frc4467,2025,2025tnkn,2025tnkn_qm40,40,4/4/2025 7:16:00 PM,red,frc3821,3,2,0,5,0,1,1,0,0,0,150,0.0,Processor Side,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,150,0,Not Parked,1,0,0,0
237,frc4467,2025,2025tnkn,2025tnkn_qm40,40,4/4/2025 7:16:00 PM,blue,frc4630,3,0,0,3,0,0,0,0,0,0,0,0.0,Processor Side,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
243,frc4467,2025,2025tnkn,2025tnkn_qm41,41,4/4/2025 7:24:00 PM,blue,frc3843,10,10,0,20,1,0,1,0,2,2,0,0.0,Middle,1,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,Not Parked,1,0,0,0
249,frc4467,2025,2025tnkn,2025tnkn_qm42,42,4/4/2025 7:32:00 PM,blue,frc4306,3,0,2,5,0,0,0,0,0,0,7,0.0,Middle,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,14,7,Parked,1,0,0,0
287,frc4467,2025,2025tnkn,2025tnkn_qm48,48,4/4/2025 8:20:00 PM,red,frc4630,3,8,0,11,0,2,2,0,0,0,0,0.0,Processor Side,1,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
337,frc4467,2025,2025tnkn,2025tnkn_qm57,57,4/4/2025 9:32:00 PM,blue,frc5744,10,0,0,10,1,0,1,0,0,0,-27,0.0,Middle,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,27,Not Parked,1,0,0,0
341,frc4467,2025,2025tnkn,2025tnkn_qm57,57,4/4/2025 9:32:00 PM,red,frc2856,3,0,0,3,0,0,0,0,0,0,0,0.0,Cage Side,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
361,frc4467,2025,2025tnkn,2025tnkn_qm61,61,4/5/2025 1:17:00 PM,blue,frc5045,9,12,0,21,1,3,4,0,0,0,150,0.5,Middle,1,0,1,0,0,0,0,0,3,0,0,0,0,0,0,0,0,150,0,Not Parked,1,1,0,0
374,frc4467,2025,2025tnkn,2025tnkn_qm63,63,4/5/2025 1:35:00 PM,blue,frc10101,3,0,0,3,0,0,0,0,0,0,150,0.0,Middle,1,0,0,0,0,0,0,0,0,0,0,0,0,0,7,0,0,150,0,Not Parked,1,0,0,0
383,frc4467,2025,2025tnkn,2025tnkn_qm64,64,4/5/2025 1:44:00 PM,red,frc2856,0,2,0,2,0,1,1,0,0,0,150,0.0,Middle,0,0,0,0,0,0,0,0,0,0,1,0,0,1,2,0,0,150,0,Not Parked,1,0,0,0
394,frc4467,2025,2025tnkn,2025tnkn_qm66,66,4/5/2025 2:02:00 PM,red,frc4630,0,4,0,4,0,1,1,0,0,0,0,0.5,Not There,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,Not Parked,1,1,0,0
398,frc4467,2025,2025tnkn,2025tnkn_qm67,67,4/5/2025 2:10:00 PM,red,frc3492,3,19,0,22,0,6,6,0,0,0,0,0.0,Middle,1,0,0,0,0,0,0,0,2,3,1,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
442,frc4467,2025,2025tnkn,2025tnkn_qm75,75,4/5/2025 3:14:00 PM,red,frc10137,3,0,2,5,0,0,0,0,0,0,3,0.5,Processor Side,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,Parked,1,1,0,0
446,frc4467,2025,2025tnkn,2025tnkn_qm75,75,4/5/2025 3:14:00 PM,red,frc2856,3,0,0,3,0,0,0,0,0,0,150,0.0,Middle,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,150,0,Not Parked,1,0,0,0
457,frc4467,2025,2025tnkn,2025tnkn_qm77,77,4/5/2025 3:30:00 PM,blue,frc5045,9,8,0,17,1,2,3,0,0,0,0,0.0,Middle,1,0,1,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
460,frc4467,2025,2025tnkn,2025tnkn_qm78,78,4/5/2025 3:38:00 PM,blue,frc9152,3,0,0,3,0,0,0,0,0,0,0,0.0,Processor Side,1,0,0,0,0,0,0,0,0,0,0,0,0,1,5,0,0,0,0,Not Parked,1,0,0,0
470,frc4467,2025,2025tnkn,2025tnkn_qm79,79,4/5/2025 3:46:00 PM,blue,frc7072,17,30,0,47,2,6,8,0,0,0,0,0.0,Cage Side,1,2,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0

In [48]:
"""
Step 3b. Query for all the instances when a team scored more than 8 pieces of coral
"""
scouted_data["totalCoral"]=scouted_data["autoCoralL4"]+scouted_data["autoCoralL3"]+scouted_data["autoCoralL2"]+scouted_data["autoCoralL1"]+scouted_data["teleopCoralL4"]+scouted_data["autoCoralL3"]+scouted_data["autoCoralL2"]
scouted_data[scouted_data["totalCoral"]>8]

,org_key,year,event_key,match_key,match_number,time,alliance,team_key,totalAutoPoints,totalTeleopPoints,totalEndgamePoints,contributedPoints,totalAutoCoral,totalTeleopCoral,totalCoral,totalAutoAlgae,totalTeleopAlgae,totalAlgae,ClimbTime,Reliability,startingPosition,didLeaveStartingZone,autoCoralL4,autoCoralL3,autoCoralL2,autoCoralL1,autoAlgaeProc,autoAlgaeNet,teleopCoralL4,teleopCoralL3,teleopCoralL2,teleopCoralL1,teleopAlgaeProc,teleopAlgaeNet,didDefense,Defenserating,totalMinorFouls,totalMajorFouls,climbingStartTime,climbingStopTime,bargeStatus,diedDuringMatch,recoveredFromFreeze,didYellowCard,didRedCard
104,frc4467,2025,2025tnkn,2025tnkn_qm18,18,4/4/2025 3:14:00 PM,red,frc10479,10,40,2,52,1,8,9,0,0,0,150,1.0,Processor Side,1,1,0,0,0,0,0,8,0,0,0,0,0,0,0,0,0,150,0,Parked,0,0,0,0
115,frc4467,2025,2025tnkn,2025tnkn_qm20,20,4/4/2025 3:30:00 PM,blue,frc3937,3,63,12,78,0,15,9,0,0,0,4,1.0,Processor Side,1,0,0,0,0,0,0,9,3,0,3,0,0,0,0,0,0,6,2,Deep Cage,0,0,0,0
143,frc4467,2025,2025tnkn,2025tnkn_qm24,24,4/4/2025 5:08:00 PM,blue,frc7072,21,40,12,73,3,8,11,0,0,0,-3,1.0,Cage Side,0,3,0,0,0,0,0,8,0,0,0,0,0,0,0,0,0,143,146,Deep Cage,0,0,0,0
146,frc4467,2025,2025tnkn,2025tnkn_qm25,25,4/4/2025 5:16:00 PM,red,frc4065,17,37,12,66,2,8,9,0,0,0,11,1.0,Processor Side,1,2,0,0,0,0,0,7,0,0,1,0,0,0,0,0,0,16,5,Deep Cage,0,0,0,0
163,frc4467,2025,2025tnkn,2025tnkn_qm28,28,4/4/2025 5:40:00 PM,red,frc4467,17,58,0,75,2,13,10,0,0,0,150,1.0,Cage Side,1,2,0,0,0,0,0,8,3,2,0,0,0,0,0,0,0,150,0,Not Parked,0,0,0,0
221,frc4467,2025,2025tnkn,2025tnkn_qm37,37,4/4/2025 6:52:00 PM,blue,frc7072,24,37,2,63,3,8,10,0,0,0,7,1.0,Processor Side,1,3,0,0,0,0,0,7,0,0,1,0,0,0,0,0,0,7,0,Parked,0,0,0,0
233,frc4467,2025,2025tnkn,2025tnkn_qm39,39,4/4/2025 7:08:00 PM,blue,frc5847,17,50,2,69,2,11,9,0,0,0,0,1.0,Cage Side,1,2,0,0,0,0,0,7,3,1,0,0,0,0,0,0,0,0,0,Parked,0,0,0,0
244,frc4467,2025,2025tnkn,2025tnkn_qm41,41,4/4/2025 7:24:00 PM,red,frc3504,17,35,2,54,2,7,9,0,0,0,0,1.0,Processor Side,1,2,0,0,0,0,0,7,0,0,0,0,0,0,0,0,0,0,0,Parked,0,0,0,0
273,frc4467,2025,2025tnkn,2025tnkn_qm46,46,4/4/2025 8:04:00 PM,blue,frc4065,17,58,12,87,2,8,10,0,3,3,4,1.0,Processor Side,1,2,0,0,0,0,0,8,0,0,0,3,0,0,0,0,0,5,1,Deep Cage,0,0,0,0
274,frc4467,2025,2025tnkn,2025tnkn_qm46,46,4/4/2025 8:04:00 PM,red,frc5847,7,53,2,62,1,11,10,0,0,0,150,1.0,Processor Side,0,1,0,0,0,0,0,9,2,0,0,0,0,0,0,0,0,150,0,Parked,0,0,0,0
324,frc4467,2025,2025tnkn,2025tnkn_qm55,55,4/4/2025 9:16:00 PM,red,frc801,17,56,2,75,2,9,10,0,2,2,16,1.0,Processor Side,1,2,0,0,0,0,0,8,1,0,0,2,0,0,0,0,0,16,0,Parked,0,0,0,0
347,frc4467,2025,2025tnkn,2025tnkn_qm58,58,4/5/2025 12:50:00 PM,blue,frc4265,17,57,12,86,2,12,11,0,0,0,15,1.0,Cage Side,1,2,0,0,0,0,0,9,3,0,0,0,0,0,0,0,0,18,3,Deep Cage,0,0,0,0
381,frc4467,2025,2025tnkn,2025tnkn_qm64,64,4/5/2025 1:44:00 PM,red,frc5847,17,64,2,83,2,11,11,0,3,3,2,1.0,Cage Side,1,2,0,0,0,0,0,9,1,1,0,0,3,0,0,0,0,2,0,Parked,0,0,0,0
396,frc4467,2025,2025tnkn,2025tnkn_qm67,67,4/5/2025 2:10:00 PM,blue,frc3966,10,61,2,73,1,13,10,0,0,0,0,1.0,Processor Side,1,1,0,0,0,0,0,9,4,0,0,0,0,0,0,0,0,0,0,Parked,0,0,0,0
426,frc4467,2025,2025tnkn,2025tnkn_qm72,72,4/5/2025 2:50:00 PM,red,frc4020,17,69,2,88,2,13,13,0,1,1,150,1.0,Processor Side,1,2,0,0,0,0,0,11,2,0,0,1,0,0,0,0,0,150,0,Parked,0,0,0,0
445,frc4467,2025,2025tnkn,2025tnkn_qm75,75,4/5/2025 3:14:00 PM,blue,frc2393,3,45,0,48,0,9,9,0,0,0,0,1.0,Cage Side,1,0,0,0,0,0,0,9,0,0,0,0,0,0,0,0,0,0,0,Not Parked,0,0,0,0
459,frc4467,2025,2025tnkn,2025tnkn_qm77,77,4/5/2025 3:30:00 PM,blue,frc4576,32,0,2,34,5,0,9,1,0,1,0,1.0,Processor Side,1,0,2,2,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,Parked,0,0,0,0

In [50]:
"""
Step XXXX. Calculate the averages stats per team and display them
"""
scouted_data.groupby("team_key").mean(numeric_only=True)

,year,match_number,totalAutoPoints,totalTeleopPoints,totalEndgamePoints,contributedPoints,totalAutoCoral,totalTeleopCoral,totalCoral,totalAutoAlgae,totalTeleopAlgae,totalAlgae,ClimbTime,Reliability,didLeaveStartingZone,autoCoralL4,autoCoralL3,autoCoralL2,autoCoralL1,autoAlgaeProc,autoAlgaeNet,teleopCoralL4,teleopCoralL3,teleopCoralL2,teleopCoralL1,teleopAlgaeProc,teleopAlgaeNet,didDefense,Defenserating,totalMinorFouls,totalMajorFouls,climbingStartTime,climbingStopTime,diedDuringMatch,recoveredFromFreeze,didYellowCard,didRedCard
team_key,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
frc10101,2025.0,37.700000,2.400000,3.600000,6.200000,12.200000,0.000000,0.800000,0.600000,0.0,0.000000,0.000000,36.300000,0.800000,0.800000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.600000,0.000000,0.200000,0.000000,0.000000,0.000000,0.600000,3.600000,0.2,0.0,38.500000,2.200000,0.200000,0.0,0.0,0.0
frc10137,2025.0,41.300000,3.000000,3.600000,1.400000,8.000000,0.000000,0.000000,0.000000,0.0,0.600000,0.600000,33.400000,0.950000,1.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.600000,0.000000,0.300000,0.900000,0.0,0.0,33.500000,0.100000,0.100000,0.1,0.0,0.0
frc1014,2025.0,39.400000,5.000000,16.000000,9.400000,30.400000,0.400000,0.500000,0.700000,0.0,2.800000,2.800000,14.300000,1.000000,1.000000,0.200000,0.0,0.0,0.200000,0.0,0.0,0.300000,0.000000,0.100000,0.100000,1.400000,1.400000,0.200000,1.100000,0.1,0.0,19.400000,5.100000,0.000000,0.0,0.0,0.0
frc10269,2025.0,41.700000,2.700000,0.200000,1.000000,3.900000,0.000000,0.100000,0.000000,0.0,0.000000,0.000000,2.100000,0.900000,0.900000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.100000,0.000000,0.000000,0.500000,1.600000,0.0,0.0,2.100000,0.000000,0.100000,0.0,0.0,0.0
frc10479,2025.0,39.600000,15.700000,42.100000,7.200000,65.000000,1.600000,9.700000,5.900000,0.4,0.500000,0.900000,20.500000,1.050000,0.900000,1.600000,0.0,0.0,0.000000,0.1,0.3,4.300000,2.200000,3.000000,0.200000,0.200000,0.300000,0.000000,0.000000,0.0,0.0,21.900000,1.400000,0.000000,0.1,0.0,0.0
frc1466,2025.0,39.300000,7.200000,24.100000,0.800000,32.100000,0.700000,3.400000,2.800000,0.0,1.700000,1.700000,77.200000,1.000000,0.900000,0.600000,0.0,0.0,0.100000,0.0,0.0,2.100000,0.800000,0.200000,0.300000,1.200000,0.500000,0.000000,0.000000,0.0,0.0,77.200000,0.000000,0.000000,0.0,0.0,0.0
frc1592,2025.0,38.800000,4.700000,29.100000,8.800000,42.600000,0.300000,5.000000,3.200000,0.0,1.300000,1.300000,36.200000,0.950000,1.000000,0.200000,0.0,0.0,0.100000,0.0,0.0,2.900000,0.800000,1.000000,0.300000,1.300000,0.000000,0.000000,0.000000,0.0,0.0,37.500000,1.300000,0.100000,0.1,0.0,0.0
frc1708,2025.0,41.500000,3.700000,35.800000,2.200000,41.700000,0.200000,8.100000,5.300000,0.0,0.100000,0.100000,48.100000,1.000000,0.900000,0.100000,0.0,0.0,0.100000,0.0,0.0,5.100000,1.500000,0.700000,0.800000,0.100000,0.000000,0.000000,0.000000,0.0,0.0,48.100000,0.000000,0.000000,0.0,0.0,0.0
frc21,2025.0,39.800000,10.300000,21.600000,8.800000,40.700000,1.100000,4.800000,4.900000,0.0,0.000000,0.000000,13.400000,1.000000,1.000000,1.000000,0.0,0.0,0.100000,0.0,0.0,3.800000,0.300000,0.000000,0.700000,0.000000,0.000000,0.000000,0.800000,0.0,0.0,17.300000,3.900000,0.000000,0.0,0.0,0.0
frc233,2025.0,39.100000,12.400000,41.600000,7.800000,61.800000,1.400000,10.200000,4.900000,0.0,0.100000,0.100000,22.900000,1.000000,1.000000,1.300000,0.0,0.0,0.100000,0.0,0.0,3.500000,4.200000,1.700000,0.800000,0.100000,0.000000,0.000000,0.000000,0.0,0.0,24.000000,1.100000,0.000000,0.0,0.0,0.0
frc2393,2025.0,40.900000,6.800000,32.200000,0.600000,39.600000,0.600000,7.300000,4.700000,0.0,0.000000,0.000000,16.100000,1.000000,1.000000,0.500000,0.0,0.0,0.100000,0.0,0.0,4.100000,2.200000,0.900000,0.100000,0.000000,0.000000,0.000000,0.000000,0.1,0.0,16.400000,0.300000,0.000000,0.0,0.0,0.0
frc2614,2025.0,39.400000,10.100000,22.400000,6.400000,38.900000,1.100000,5.400000,3.400000,0.0,0.100000,0.100000,3.000000,1.000000,0.900000,1.000000,0.0,0.1,0.000000,0.0,0.0,2.200000,1.600000,1.200000,0.400000,0.100000,0.000000,0.000000,0.000000,0.0,0.0,20.100000,17.100000,0.000000,0.0,0.0,0.0
frc2856,2025.0,38.600000,1.500000,0.200000,0.200000,1.900000,0.000000,0.100000,0.000000,0.0,0.000000,0.000000,45.000000,0.500000,0.500000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.100000,0.000000,0.000000,0.400000,1.200000,0.0,0.0,45.000000,0.000000,0.500000,0.0,0.0,0.0
frc3139,2025.0,42.363636,2.454545,11.818182,1.454545,15.727273,0.000000,5.818182,0.000000,0.0,0.000000,0.000000,1.363636,1.000000,0.818182,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.181818,5.636364,0.000000,0.000000,0.272727,1.636364,0.0,0.0,1.727273,0.363636,0.000000,0.0,0.0,0.0
frc3140,2025.0,39.600000,3.700000,24.400000,0.800000,28.900000,0.100000,4.300000,2.200000,0.0,1.200000,1.200000,30.400000,1.000000,1.000000,0.100000,0.0,0.0,0.000000,0.0,0.0,2.100000,1.100000,0.900000,0.200000,0.800000,0.400000,0.100000,0.200000,0.1,0.0,30.800000,0.400000,0.000000,0.0,0.0,0.0
frc3324,2025.0,39.700000,7.400000,28.700000,0.400000,36.500000,0.700000,7.400000,3.600000,0.0,0.000000,0.000000,45.000000,1.000000,1.000000,0.500000,0.1,0.0,0.100000,0.0,0.0,2.800000,2.400000,0.700000,1.500000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,45.000000,0.000000,0.000000,0.0,0.0,0.0
frc3492,2025.0,39.900000,4.600000,24.400000,0.600000,29.600000,0.400000,7.700000,0.800000,0.0,0.100000,0.100000,31.000000,0.900000,1.000000,0.000000,0.0,0.4,0.000000,0.0,0.0,0.000000,2.600000,3.200000,1.900000,0.100000,0.000000,0.000000,0.000000,0.0,0.0,31.000000,0.000000,0.100000,0.0,0.0,0.0
frc3504,2025.0,39.700000,15.600000,26.400000,1.800000,43.800000,1.800000,6.000000,5.400000,0.1,0.000000,0.100000,1.300000,1.000000,0.800000,1.800000,0.0,0.0,0.000000,0.1,0.0,3.600000,1.600000,0.400000,0.400000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,2.100000,0.800000,0.000000,0.0,0.0,0.0
frc3821,2025.0,39.300000,3.400000,3.400000,1.400000,8.200000,0.100000,1.700000,0.100000,0.0,0.000000,0.000000,30.900000,0.900000,0.900000,0.100000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,1.700000,0.000000,0.000000,0.700000,3.200000,0.2,0.0,30.900000,0.000000,0.100000,0.0,0.0,0.0
frc3824,2025.0,38.700000,5.700000,16.300000,5.400000,27.400000,0.600000,1.600000,1.100000,0.0,2.600000,2.600000,21.400000,1.000000,0.900000,0.300000,0.0,0.0,0.300000,0.0,0.0,0.500000,0.200000,0.000000,0.900000,0.400000,2.200000,0.000000,0.200000,0.0,0.0,51.100000,29.700000,0.000000,0.0,0.0,0.0
frc3843,2025.0,40.909091,4.181818,11.272727,6.181818,21.636364,0.545455,0.454545,0.545455,0.0,2.181818,2.181818,20.181818,0.909091,0.727273,0.090909,0.0,0.0,0.454545,0.0,0.0,0.000000,0.000000,0.000000,0.454545,0.818182,1.363636,0.000000,0.000000,0.0,0.0,23.636364,3.454545,0.090909,0.0,0.0,0.0
frc3937,2025.0,39.800000,7.600000,36.600000,9.800000,54.000000,0.800000,7.200000,3.800000,0.0,1.700000,1.700000,5.900000,0.900000,0.800000,0.700000,0.0,0.0,0.100000,0.0,0.0,3.000000,2.200000,0.400000,1.600000,0.800000,0.900000,0.000000,0.000000,0.0,0.0,8.500000,2.600000,0.100000,0.0,0.0,0.0
frc3966,2025.0,39.000000,13.200000,40.500000,1.200000,54.900000,1.600000,10.000000,5.300000,0.0,0.000000,0.000000,45.900000,1.000000,0.800000,1.500000,0.0,0.0,0.100000,0.0,0.0,3.700000,3.600000,2.200000,0.500000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,45.900000,0.000000,0.000000,0.0,0.0,0.0
frc3984,2025.0,39.100000,5.200000,11.700000,1.200000,18.100000,0.400000,3.300000,1.200000,0.0,0.000000,0.000000,31.600000,1.000000,0.800000,0.400000,0.0,0.0,0.000000,0.0,0.0,0.800000,1.000000,0.700000,0.800000,0.000000,0.000000,0.200000,0.400000,0.0,0.0,32.400000,0.800000,0.000000,0.0,0.0,0.0
frc4020,2025.0,39.100000,22.300000,54.700000,8.200000,85.200000,2.800000,11.000000,6.600000,0.0,1.900000,1.900000,19.400000,1.000000,0.900000,2.800000,0.0,0.0,0.000000,0.0,0.0,3.800000,4.100000,2.700000,0.400000,1.400000,0.500000,0.000000,0.000000,0.0,0.0,35.100000,15.700000,0.000000,0.0,0.0,0.0
frc4065,2025.0,37.222222,14.555556,33.888889,8.666667,57.111111,1.777778,2.888889,4.333333,0.0,4.222222,4.222222,10.111111,1.000000,1.000000,1.555556,0.0,0.0,0.222222,0.0,0.0,2.555556,0.111111,0.000000,0.222222,1.666667,2.555556,0.111111,0.222222,0.0,0.0,13.444444,3.333333,0.000000,0.0,0.0,0.0
frc4265,2025.0,39.400000,13.800000,38.000000,8.800000,60.600000,1.700000,8.400000,5.900000,0.0,0.400000,0.400000,8.400000,1.000000,0.900000,1.500000,0.0,0.0,0.200000,0.0,0.0,4.200000,2.900000,1.200000,0.100000,0.000000,0.400000,0.000000,0.000000,0.0,0.0,11.200000,2.800000,0.000000,0.0,0.0,0.0
frc4306,2025.0,40.200000,2.400000,0.000000,1.400000,3.800000,0.100000,0.000000,0.200000,0.0,0.000000,0.000000,22.400000,0.700000,0.600000,0.000000,0.1,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,1.600000,0.6,0.0,23.100000,0.700000,0.300000,0.0,0.0,0.0
frc4467,2025.0,40.000000,11.100000,35.700000,7.000000,53.800000,1.200000,7.900000,4.400000,0.0,0.700000,0.700000,23.000000,1.000000,0.900000,1.200000,0.0,0.0,0.000000,0.0,0.0,3.200000,2.000000,2.100000,0.600000,0.700000,0.000000,0.000000,0.000000,0.0,0.0,38.200000,15.200000,0.000000,0.0,0.0,0.0
frc4504,2025.0,41.300000,1.200000,1.400000,1.200000,3.800000,0.000000,0.700000,0.000000,0.0,0.000000,0.000000,30.200000,1.000000,0.400000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.700000,0.000000,0.000000,0.200000,0.500000,0.0,0.0,30.200000,0.000000,0.000000,0.0,0.0,0.0
frc4576,2025.0,40.200000,7.700000,11.100000,0.800000,19.600000,0.800000,1.800000,2.100000,0.1,1.000000,1.100000,31.000000,1.000000,0.900000,0.300000,0.2,0.2,0.100000,0.1,0.0,0.900000,0.400000,0.000000,0.500000,0.000000,1.000000,0.000000,0.000000,0.0,0.0,31.000000,0.000000,0.000000,0.0,0.0,0.0
frc4630,2025.0,37.400000,2.800000,5.600000,1.000000,9.400000,0.000000,1.500000,0.000000,0.1,0.000000,0.100000,3.300000,0.750000,0.800000,0.000000,0.0,0.0,0.000000,0.0,0.1,0.000000,1.200000,0.200000,0.100000,0.000000,0.000000,0.200000,0.700000,0.1,0.0,4.800000,1.500000,0.300000,0.1,0.0,0.0
frc5002,2025.0,43.727273,4.545455,18.545455,4.363636,27.454545,0.272727,4.272727,2.545455,0.0,0.000000,0.000000,32.545455,0.818182,1.000000,0.181818,0.0,0.0,0.090909,0.0,0.0,2.272727,1.363636,0.454545,0.181818,0.000000,0.000000,0.090909,0.000000,0.0,0.0,32.727273,0.181818,0.181818,0.0,0.0,0.0
frc5045,2025.0,39.900000,4.800000,10.600000,1.800000,17.200000,0.400000,3.200000,0.700000,0.0,0.000000,0.000000,32.300000,0.850000,0.900000,0.000000,0.3,0.0,0.100000,0.0,0.0,0.000000,2.100000,0.000000,1.100000,0.000000,0.000000,0.200000,0.800000,0.0,0.0,33.200000,0.900000,0.200000,0.1,0.0,0.0
frc538,2025.0,38.300000,3.400000,7.800000,4.600000,15.800000,0.100000,0.000000,0.100000,0.0,1.500000,1.500000,25.400000,0.900000,0.900000,0.100000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.900000,0.600000,0.300000,2.800000,0.0,0.0,27.100000,1.700000,0.100000,0.0,0.0,0.0
frc5744,2025.0,38.000000,3.400000,0.000000,1.200000,4.600000,0.100000,0.000000,0.100000,0.0,0.000000,0.000000,14.100000,0.800000,0.900000,0.100000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.600000,3.100000,0.0,0.0,17.600000,3.500000,0.200000,0.0,0.0,0.0
frc5816,2025.0,40.200000,8.200000,17.800000,4.000000,30.000000,0.800000,4.600000,3.300000,0.0,0.000000,0.000000,7.100000,1.000000,1.000000,0.700000,0.0,0.0,0.100000,0.0,0.0,2.500000,0.300000,0.500000,1.300000,0.000000,0.000000,0.000000,0.900000,0.0,0.0,7.900000,0.800000,0.000000,0.0,0.0,0.0
frc5847,2025.0,39.900000,10.100000,52.500000,1.600000,64.200000,1.100000,11.100000,7.400000,0.0,0.900000,0.900000,31.000000,1.000000,0.800000,1.100000,0.0,0.0,0.000000,0.0,0.0,6.300000,2.900000,1.200000,0.700000,0.400000,0.500000,0.000000,0.000000,0.0,0.0,31.000000,0.000000,0.000000,0.0,0.0,0.0
frc6517,2025.0,37.333333,12.000000,32.555556,8.666667,53.222222,1.444444,7.666667,4.444444,0.0,0.111111,0.111111,11.000000,0.888889,0.777778,1.333333,0.0,0.0,0.111111,0.0,0.0,3.000000,3.333333,0.888889,0.444444,0.111111,0.000000,0.000000,0.000000,0.0,0.0,14.444444,3.444444,0.111111,0.0,0.0,0.0
frc7072,2025.0,41.600000,21.000000,30.400000,6.800000,58.200000,2.700000,6.900000,6.900000,0.0,0.000000,0.000000,21.300000,0.900000,0.700000,2.700000,0.0,0.0,0.000000,0.0,0.0,4.200000,1.600000,0.800000,0.300000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,36.000000,14.700000,0.100000,0.0,0.0,0.0
frc7255,2025.0,38.400000,2.700000,12.000000,0.600000,15.300000,0.000000,3.600000,0.100000,0.0,0.000000,0.000000,61.900000,1.050000,0.900000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.100000,1.400000,1.700000,0.400000,0.000000,0.000000,0.200000,0.700000,0.0,0.0,62.000000,0.100000,0.000000,0.1,0.0,0.0
frc7428,2025.0,40.400000,4.000000,32.800000,7.800000,44.600000,0.300000,7.400000,2.600000,0.0,0.600000,0.600000,23.500000,1.000000,0.900000,0.100000,0.0,0.0,0.200000,0.0,0.0,2.300000,3.100000,1.300000,0.700000,0.600000,0.000000,0.000000,0.000000,0.0,0.0,24.100000,0.600000,0.000000,0.0,0.0,0.0
frc7483,2025.0,39.400000,4.400000,13.200000,5.400000,23.000000,0.200000,2.500000,1.600000,0.0,0.700000,0.700000,23.200000,0.950000,1.000000,0.200000,0.0,0.0,0.000000,0.0,0.0,1.400000,0.300000,0.600000,0.200000,0.000000,0.700000,0.100000,0.500000,0.0,0.0,28.300000,5.100000,0.100000,0.1,0.0,0.0
frc801,2025.0,41.500000,12.100000,40.400000,5.800000,58.300000,1.300000,8.500000,5.900000,0.0,0.700000,0.700000,22.400000,1.000000,1.000000,1.300000,0.0,0.0,0.000000,0.0,0.0,4.600000,2.400000,0.800000,0.700000,0.600000,0.100000,0.000000,0.000000,0.0,0.0,24.100000,1.700000,0.000000,0.0,0.0,0.0
frc8570,2025.0,39.400000,12.800000,38.800000,8.000000,59.600000,1.900000,10.700000,3.700000,0.0,0.500000,0.500000,10.400000,1.000000,0.700000,0.000000,1.6,0.2,0.100000,0.0,0.0,0.000000,5.300000,3.800000,1.600000,0.500000,0.000000,0.100000,0.500000,0.0,0.0,12.100000,1.700000,0.000000,0.0,0.0,0.0
frc9152,2025.0,40.600000,1.500000,6.000000,2.600000,10.100000,0.000000,1.400000,0.000000,0.0,0.300000,0.300000,8.900000,0.900000,0.500000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.500000,0.400000,0.500000,0.300000,0.000000,0.300000,1.200000,0.0,0.1,10.600000,1.700000,0.100000,0.0,0.0,0.0
frc9668,2025.0,40.600000,2.400000,11.700000,1.600000,15.700000,0.000000,0.600000,0.000000,0.0,1.700000,1.700000,48.100000,1.000000,0.800000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.300000,0.300000,1.700000,0.000000,0.100000,0.200000,0.0,0.0,51.100000,3.000000,0.000000,0.0,0.0,0.0

In [52]:
"""
Step XXXX. Filter teams that scored an average of more than 2 pieces of algae
"""
avg=scouted_data.groupby("team_key").mean(numeric_only=True)
avg[avg["totalAlgae"]>2]

,year,match_number,totalAutoPoints,totalTeleopPoints,totalEndgamePoints,contributedPoints,totalAutoCoral,totalTeleopCoral,totalCoral,totalAutoAlgae,totalTeleopAlgae,totalAlgae,ClimbTime,Reliability,didLeaveStartingZone,autoCoralL4,autoCoralL3,autoCoralL2,autoCoralL1,autoAlgaeProc,autoAlgaeNet,teleopCoralL4,teleopCoralL3,teleopCoralL2,teleopCoralL1,teleopAlgaeProc,teleopAlgaeNet,didDefense,Defenserating,totalMinorFouls,totalMajorFouls,climbingStartTime,climbingStopTime,diedDuringMatch,recoveredFromFreeze,didYellowCard,didRedCard
team_key,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
frc1014,2025.0,39.400000,5.000000,16.000000,9.400000,30.400000,0.400000,0.500000,0.700000,0.0,2.800000,2.800000,14.300000,1.000000,1.000000,0.200000,0.0,0.0,0.200000,0.0,0.0,0.300000,0.000000,0.1,0.100000,1.400000,1.400000,0.200000,1.100000,0.1,0.0,19.400000,5.100000,0.000000,0.0,0.0,0.0
frc3824,2025.0,38.700000,5.700000,16.300000,5.400000,27.400000,0.600000,1.600000,1.100000,0.0,2.600000,2.600000,21.400000,1.000000,0.900000,0.300000,0.0,0.0,0.300000,0.0,0.0,0.500000,0.200000,0.0,0.900000,0.400000,2.200000,0.000000,0.200000,0.0,0.0,51.100000,29.700000,0.000000,0.0,0.0,0.0
frc3843,2025.0,40.909091,4.181818,11.272727,6.181818,21.636364,0.545455,0.454545,0.545455,0.0,2.181818,2.181818,20.181818,0.909091,0.727273,0.090909,0.0,0.0,0.454545,0.0,0.0,0.000000,0.000000,0.0,0.454545,0.818182,1.363636,0.000000,0.000000,0.0,0.0,23.636364,3.454545,0.090909,0.0,0.0,0.0
frc4065,2025.0,37.222222,14.555556,33.888889,8.666667,57.111111,1.777778,2.888889,4.333333,0.0,4.222222,4.222222,10.111111,1.000000,1.000000,1.555556,0.0,0.0,0.222222,0.0,0.0,2.555556,0.111111,0.0,0.222222,1.666667,2.555556,0.111111,0.222222,0.0,0.0,13.444444,3.333333,0.000000,0.0,0.0,0.0

In [54]:
"""
Step XXXX. Query for ALL the scouted data for the teams listed in the array
"""

teams_in_match = ["frc21", "frc3824", "frc5045", "frc1466", "frc4630", "frc5744"]
filtered_scouted_data = scouted_data[scouted_data["team_key"].isin(teams_in_match)]
filtered_scouted_data

,org_key,year,event_key,match_key,match_number,time,alliance,team_key,totalAutoPoints,totalTeleopPoints,totalEndgamePoints,contributedPoints,totalAutoCoral,totalTeleopCoral,totalCoral,totalAutoAlgae,totalTeleopAlgae,totalAlgae,ClimbTime,Reliability,startingPosition,didLeaveStartingZone,autoCoralL4,autoCoralL3,autoCoralL2,autoCoralL1,autoAlgaeProc,autoAlgaeNet,teleopCoralL4,teleopCoralL3,teleopCoralL2,teleopCoralL1,teleopAlgaeProc,teleopAlgaeNet,didDefense,Defenserating,totalMinorFouls,totalMajorFouls,climbingStartTime,climbingStopTime,bargeStatus,diedDuringMatch,recoveredFromFreeze,didYellowCard,didRedCard
0,frc4467,2025,2025tnkn,2025tnkn_qm1,1,4/4/2025 12:50:00 PM,blue,frc21,10,29,12,51,1,7,4,0,0,0,16,1.0,Cage Side,1,1,0,0,0,0,0,3,3,0,1,0,0,0,0,0,0,21,5,Deep Cage,0,0,0,0
1,frc4467,2025,2025tnkn,2025tnkn_qm1,1,4/4/2025 12:50:00 PM,blue,frc3824,6,18,12,36,1,2,1,0,3,3,20,1.0,Middle,1,0,0,0,1,0,0,0,1,0,1,0,3,0,0,0,0,20,0,Deep Cage,0,0,0,0
2,frc4467,2025,2025tnkn,2025tnkn_qm1,1,4/4/2025 12:50:00 PM,red,frc5045,0,4,0,4,0,1,0,0,0,0,0,1.0,Middle,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,Not Parked,0,0,0,0
3,frc4467,2025,2025tnkn,2025tnkn_qm1,1,4/4/2025 12:50:00 PM,blue,frc1466,6,26,0,32,1,6,5,0,0,0,0,1.0,Processor Side,1,0,0,0,1,0,0,4,1,0,1,0,0,0,0,0,0,0,0,Not Parked,0,0,0,0
4,frc4467,2025,2025tnkn,2025tnkn_qm1,1,4/4/2025 12:50:00 PM,red,frc4630,7,8,2,17,0,2,0,1,0,1,0,1.0,Processor Side,1,0,0,0,0,0,1,0,2,0,0,0,0,0,0,0,0,0,0,Parked,0,0,0,0
5,frc4467,2025,2025tnkn,2025tnkn_qm1,1,4/4/2025 12:50:00 PM,red,frc5744,0,0,2,2,0,0,0,0,0,0,0,1.0,Not There,0,0,0,0,0,0,0,0,0,0,0,0,0,1,6,0,0,0,0,Parked,0,0,0,0
48,frc4467,2025,2025tnkn,2025tnkn_qm9,9,4/4/2025 2:02:00 PM,red,frc5045,3,22,0,25,0,6,0,0,0,0,0,1.0,Middle,1,0,0,0,0,0,0,0,5,0,1,0,0,0,0,0,0,0,0,Not Parked,0,0,0,0
50,frc4467,2025,2025tnkn,2025tnkn_qm9,9,4/4/2025 2:02:00 PM,red,frc1466,3,29,0,32,0,5,3,0,1,1,150,1.0,Cage Side,1,0,0,0,0,0,0,3,2,0,0,1,0,0,0,0,0,150,0,Not Parked,0,0,0,0
54,frc4467,2025,2025tnkn,2025tnkn_qm10,10,4/4/2025 2:10:00 PM,blue,frc5744,3,0,2,5,0,0,0,0,0,0,116,0.0,Processor Side,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,116,0,Parked,1,0,0,0
57,frc4467,2025,2025tnkn,2025tnkn_qm10,10,4/4/2025 2:10:00 PM,blue,frc3824,10,12,2,24,1,0,1,0,3,3,0,1.0,Middle,1,1,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,Parked,0,0,0,0
65,frc4467,2025,2025tnkn,2025tnkn_qm11,11,4/4/2025 2:18:00 PM,red,frc4630,3,14,2,19,0,4,0,0,0,0,13,1.0,Processor Side,1,0,0,0,0,0,0,0,2,2,0,0,0,0,0,0,0,13,0,Parked,0,0,0,0
76,frc4467,2025,2025tnkn,2025tnkn_qm13,13,4/4/2025 2:34:00 PM,blue,frc21,10,24,6,40,1,6,5,0,0,0,15,1.0,Cage Side,1,1,0,0,0,0,0,4,0,0,2,0,0,0,0,0,0,15,0,Shallow Cage,0,0,0,0
93,frc4467,2025,2025tnkn,2025tnkn_qm16,16,4/4/2025 2:58:00 PM,blue,frc4630,3,2,2,7,0,1,0,0,0,0,4,1.0,Cage Side,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,7,3,Parked,0,0,0,0
106,frc4467,2025,2025tnkn,2025tnkn_qm18,18,4/4/2025 3:14:00 PM,red,frc5744,3,0,2,5,0,0,0,0,0,0,0,1.0,Middle,1,0,0,0,0,0,0,0,0,0,0,0,0,1,3,0,0,0,0,Parked,0,0,0,0
109,frc4467,2025,2025tnkn,2025tnkn_qm19,19,4/4/2025 3:22:00 PM,red,frc5045,3,2,2,7,0,1,0,0,0,0,5,1.0,Middle,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,10,5,Parked,0,0,0,0
112,frc4467,2025,2025tnkn,2025tnkn_qm19,19,4/4/2025 3:22:00 PM,red,frc21,3,22,2,27,0,5,4,0,0,0,24,1.0,Processor Side,1,0,0,0,0,0,0,4,0,0,1,0,0,0,0,0,0,24,0,Parked,0,0,0,0
114,frc4467,2025,2025tnkn,2025tnkn_qm20,20,4/4/2025 3:30:00 PM,blue,frc1466,0,22,2,24,0,3,2,0,2,2,150,1.0,Cage Side,0,0,0,0,0,0,0,2,1,0,0,0,2,0,0,0,0,150,0,Parked,0,0,0,0
137,frc4467,2025,2025tnkn,2025tnkn_qm23,23,4/4/2025 5:00:00 PM,red,frc3824,6,26,12,44,1,1,1,0,6,6,6,1.0,Middle,1,0,0,0,1,0,0,0,0,0,1,0,6,0,0,0,0,15,9,Deep Cage,0,0,0,0
139,frc4467,2025,2025tnkn,2025tnkn_qm24,24,4/4/2025 5:08:00 PM,red,frc5744,3,0,2,5,0,0,0,0,0,0,44,1.0,Processor Side,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,44,0,Parked,0,0,0,0
142,frc4467,2025,2025tnkn,2025tnkn_qm24,24,4/4/2025 5:08:00 PM,blue,frc4630,3,0,0,3,0,0,0,0,0,0,2,1.0,Middle,1,0,0,0,0,0,0,0,0,0,0,0,0,1,4,0,0,5,3,Not Parked,0,0,0,0
153,frc4467,2025,2025tnkn,2025tnkn_qm26,26,4/4/2025 5:24:00 PM,blue,frc21,10,24,6,40,1,6,5,0,0,0,18,1.0,Cage Side,1,1,0,0,0,0,0,4,0,0,2,0,0,0,0,0,0,18,0,Shallow Cage,0,0,0,0
157,frc4467,2025,2025tnkn,2025tnkn_qm27,27,4/4/2025 5:32:00 PM,blue,frc5045,3,22,12,37,0,6,0,0,0,0,7,1.0,Middle,1,0,0,0,0,0,0,0,5,0,1,0,0,0,0,0,0,11,4,Deep Cage,0,0,0,0
169,frc4467,2025,2025tnkn,2025tnkn_qm29,29,4/4/2025 5:48:00 PM,red,frc1466,3,17,2,22,0,1,1,0,2,2,9,1.0,Middle,1,0,0,0,0,0,0,1,0,0,0,2,0,0,0,0,0,9,0,Parked,0,0,0,0
175,frc4467,2025,2025tnkn,2025tnkn_qm30,30,4/4/2025 5:56:00 PM,blue,frc3824,3,4,2,9,0,0,0,0,1,1,-12,1.0,Processor Side,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,138,150,Parked,0,0,0,0
203,frc4467,2025,2025tnkn,2025tnkn_qm34,34,4/4/2025 6:28:00 PM,blue,frc4630,3,0,2,5,0,0,0,0,0,0,8,1.0,Middle,1,0,0,0,0,0,0,0,0,0,0,0,0,1,3,1,0,17,9,Parked,0,0,0,0
208,frc4467,2025,2025tnkn,2025tnkn_qm35,35,4/4/2025 6:36:00 PM,red,frc21,13,30,12,55,2,6,8,0,0,0,14,1.0,Middle,1,1,0,0,1,0,0,6,0,0,0,0,0,0,0,0,0,20,6,Deep Cage,0,0,0,0
213,frc4467,2025,2025tnkn,2025tnkn_qm36,36,4/4/2025 6:44:00 PM,blue,frc3824,10,30,2,42,1,2,3,0,4,4,-19,1.0,Middle,1,1,0,0,0,0,0,2,0,0,0,2,2,0,2,0,0,0,19,Parked,0,0,0,0
223,frc4467,2025,2025tnkn,2025tnkn_qm38,38,4/4/2025 7:00:00 PM,blue,frc1466,10,19,0,29,1,5,3,0,0,0,150,1.0,Cage Side,1,1,0,0,0,0,0,2,1,1,1,0,0,0,0,0,0,150,0,Not Parked,0,0,0,0
229,frc4467,2025,2025tnkn,2025tnkn_qm39,39,4/4/2025 7:08:00 PM,blue,frc5045,3,0,0,3,0,0,0,0,0,0,150,1.0,Middle,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,150,0,Not Parked,0,0,0,0
231,frc4467,2025,2025tnkn,2025tnkn_qm39,39,4/4/2025 7:08:00 PM,red,frc5744,3,0,0,3,0,0,0,0,0,0,0,1.0,Middle,1,0,0,0,0,0,0,0,0,0,0,0,0,1,6,0,0,0,0,Not Parked,0,0,0,0
237,frc4467,2025,2025tnkn,2025tnkn_qm40,40,4/4/2025 7:16:00 PM,blue,frc4630,3,0,0,3,0,0,0,0,0,0,0,0.0,Processor Side,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
240,frc4467,2025,2025tnkn,2025tnkn_qm41,41,4/4/2025 7:24:00 PM,red,frc3824,6,16,12,34,1,2,1,0,2,2,20,1.0,Middle,1,0,0,0,1,0,0,0,0,0,2,2,0,0,0,0,0,20,0,Deep Cage,0,0,0,0
248,frc4467,2025,2025tnkn,2025tnkn_qm42,42,4/4/2025 7:32:00 PM,red,frc21,10,2,12,24,1,1,1,0,0,0,16,1.0,Processor Side,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,16,0,Deep Cage,0,0,0,0
255,frc4467,2025,2025tnkn,2025tnkn_qm43,43,4/4/2025 7:40:00 PM,red,frc1466,10,34,0,44,1,5,5,0,2,2,150,1.0,Processor Side,1,1,0,0,0,0,0,4,0,0,1,2,0,0,0,0,0,150,0,Not Parked,0,0,0,0
260,frc4467,2025,2025tnkn,2025tnkn_qm44,44,4/4/2025 7:48:00 PM,red,frc5744,3,0,2,5,0,0,0,0,0,0,0,1.0,Middle,1,0,0,0,0,0,0,0,0,0,0,0,0,1,2,0,0,0,0,Parked,0,0,0,0
268,frc4467,2025,2025tnkn,2025tnkn_qm45,45,4/4/2025 7:56:00 PM,blue,frc5045,3,16,2,21,0,7,0,0,0,0,5,1.0,Processor Side,1,0,0,0,0,0,0,0,1,0,6,0,0,0,0,0,0,5,0,Parked,0,0,0,0
287,frc4467,2025,2025tnkn,2025tnkn_qm48,48,4/4/2025 8:20:00 PM,red,frc4630,3,8,0,11,0,2,0,0,0,0,0,0.0,Processor Side,1,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
291,frc4467,2025,2025tnkn,2025tnkn_qm49,49,4/4/2025 8:28:00 PM,blue,frc5744,3,0,0,3,0,0,0,0,0,0,0,1.0,Middle,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Not Parked,0,0,0,0
297,frc4467,2025,2025tnkn,2025tnkn_qm50,50,4/4/2025 8:36:00 PM,blue,frc3824,10,21,6,37,1,1,2,0,4,4,21,1.0,Middle,1,1,0,0,0,0,0,1,0,0,0,0,4,0,0,0,0,140,119,Shallow Cage,0,0,0,0
300,frc4467,2025,2025tnkn,2025tnkn_qm51,51,4/4/2025 8:44:00 PM,blue,frc21,10,20,12,42,1,4,5,0,0,0,4,1.0,Cage Side,1,1,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,16,12,Deep Cage,0,0,0,0
317,frc4467,2025,2025tnkn,2025tnkn_qm53,53,4/4/2025 9:00:00 PM,red,frc1466,17,33,0,50,2,5,4,0,2,2,0,1.0,Cage Side,1,2,0,0,0,0,0,2,2,1,0,2,0,0,0,0,0,0,0,Not Parked,0,0,0,0
329,frc4467,2025,2025tnkn,2025tnkn_qm55,55,4/4/2025 9:16:00 PM,red,frc5045,6,0,0,6,1,0,1,0,0,0,0,1.0,Middle,1,0,0,0,1,0,0,0,0,0,0,0,0,1,7,0,0,0,0,Not Parked,0,0,0,0
332,frc4467,2025,2025tnkn,2025tnkn_qm56,56,4/4/2025 9:24:00 PM,red,frc4630,0,8,0,8,0,2,0,0,0,0,0,1.0,Processor Side,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,Not Parked,0,0,0,0
337,frc4467,2025,2025tnkn,2025tnkn_qm57,57,4/4/2025 9:32:00 PM,blue,frc5744,10,0,0,10,1,0,1,0,0,0,-27,0.0,Middle,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,27,Not Parked,1,0,0,0
344,frc4467,2025,2025tnkn,2025tnkn_qm58,58,4/5/2025 12:50:00 PM,blue,frc1466,3,16,0,19,0,1,0,0,3,3,0,1.0,Processor Side,1,0,0,0,0,0,0,0,1,0,0,0,3,0,0,0,0,0,0,Not Parked,0,0,0,0
346,frc4467,2025,2025tnkn,2025tnkn_qm58,58,4/5/2025 12:50:00 PM,red,frc3824,0,16,2,18,0,4,0,0,2,2,8,1.0,Not There,0,0,0,0,0,0,0,0,0,0,4,0,2,0,0,0,0,8,0,Parked,0,0,0,0
361,frc4467,2025,2025tnkn,2025tnkn_qm61,61,4/5/2025 1:17:00 PM,blue,frc5045,9,12,0,21,1,3,2,0,0,0,150,0.5,Middle,1,0,1,0,0,0,0,0,3,0,0,0,0,0,0,0,0,150,0,Not Parked,1,1,0,0
372,frc4467,2025,2025tnkn,2025tnkn_qm63,63,4/5/2025 1:35:00 PM,red,frc21,10,10,12,32,1,2,3,0,0,0,17,1.0,Cage Side,1,1,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,23,6,Deep Cage,0,0,0,0
378,frc4467,2025,2025tnkn,2025tnkn_qm64,64,4/5/2025 1:44:00 PM,blue,frc3824,3,12,2,17,0,3,2,0,0,0,150,1.0,Middle,1,0,0,0,0,0,0,2,0,0,1,0,0,0,0,0,0,150,0,Parked,0,0,0,0
388,frc4467,2025,2025tnkn,2025tnkn_qm65,65,4/5/2025 1:53:00 PM,blue,frc5744,3,0,0,3,0,0,0,0,0,0,5,1.0,Middle,1,0,0,0,0,0,0,0,0,0,0,0,0,1,7,0,0,5,0,Not Parked,0,0,0,0
390,frc4467,2025,2025tnkn,2025tnkn_qm66,66,4/5/2025 2:02:00 PM,blue,frc5045,9,20,2,31,1,6,2,0,0,0,6,1.0,Middle,1,0,1,0,0,0,0,0,4,0,2,0,0,0,0,0,0,6,0,Parked,0,0,0,0
394,frc4467,2025,2025tnkn,2025tnkn_qm66,66,4/5/2025 2:02:00 PM,red,frc4630,0,4,0,4,0,1,0,0,0,0,0,0.5,Not There,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,Not Parked,1,1,0,0
400,frc4467,2025,2025tnkn,2025tnkn_qm67,67,4/5/2025 2:10:00 PM,red,frc1466,10,28,2,40,1,2,3,0,3,3,150,1.0,Cage Side,1,1,0,0,0,0,0,2,0,0,0,3,0,0,0,0,0,150,0,Parked,0,0,0,0
417,frc4467,2025,2025tnkn,2025tnkn_qm70,70,4/5/2025 2:34:00 PM,red,frc21,17,20,2,39,2,4,6,0,0,0,0,1.0,Processor Side,1,2,0,0,0,0,0,4,0,0,0,0,0,0,8,0,0,0,0,Parked,0,0,0,0
432,frc4467,2025,2025tnkn,2025tnkn_qm73,73,4/5/2025 2:58:00 PM,red,frc5744,3,0,2,5,0,0,0,0,0,0,3,1.0,Cage Side,1,0,0,0,0,0,0,0,0,0,0,0,0,1,7,0,0,11,8,Parked,0,0,0,0
437,frc4467,2025,2025tnkn,2025tnkn_qm74,74,4/5/2025 3:06:00 PM,red,frc3824,3,8,2,13,0,1,0,0,1,1,20,1.0,Middle,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,20,0,Parked,0,0,0,0
444,frc4467,2025,2025tnkn,2025tnkn_qm75,75,4/5/2025 3:14:00 PM,blue,frc1466,10,17,2,29,1,1,2,0,2,2,13,1.0,Processor Side,1,1,0,0,0,0,0,1,0,0,0,2,0,0,0,0,0,13,0,Parked,0,0,0,0
457,frc4467,2025,2025tnkn,2025tnkn_qm77,77,4/5/2025 3:30:00 PM,blue,frc5045,9,8,0,17,1,2,2,0,0,0,0,0.0,Middle,1,0,1,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,Not Parked,1,0,0,0
462,frc4467,2025,2025tnkn,2025tnkn_qm78,78,4/5/2025 3:38:00 PM,blue,frc21,10,35,12,57,1,7,8,0,0,0,10,1.0,Cage Side,1,1,0,0,0,0,0,7,0,0,0,0,0,0,0,0,0,20,10,Deep Cage,0,0,0,0
465,frc4467,2025,2025tnkn,2025tnkn_qm78,78,4/5/2025 3:38:00 PM,blue,frc4630,3,12,2,17,0,3,0,0,0,0,6,1.0,Cage Side,1,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,6,0,Parked,0,0,0,0

In [56]:
"""
Step XXXX. Query for the average scouted data for the teams listed in the array
"""

teams_in_match = ["frc21", "frc3824", "frc5045", "frc1466", "frc4630", "frc5744"]

avg=scouted_data.groupby("team_key").mean(numeric_only=True)
filtered_avg = avg[avg.index.isin(teams_in_match)]
filtered_avg

,year,match_number,totalAutoPoints,totalTeleopPoints,totalEndgamePoints,contributedPoints,totalAutoCoral,totalTeleopCoral,totalCoral,totalAutoAlgae,totalTeleopAlgae,totalAlgae,ClimbTime,Reliability,didLeaveStartingZone,autoCoralL4,autoCoralL3,autoCoralL2,autoCoralL1,autoAlgaeProc,autoAlgaeNet,teleopCoralL4,teleopCoralL3,teleopCoralL2,teleopCoralL1,teleopAlgaeProc,teleopAlgaeNet,didDefense,Defenserating,totalMinorFouls,totalMajorFouls,climbingStartTime,climbingStopTime,diedDuringMatch,recoveredFromFreeze,didYellowCard,didRedCard
team_key,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
frc1466,2025.0,39.3,7.2,24.1,0.8,32.1,0.7,3.4,2.8,0.0,1.7,1.7,77.2,1.00,0.9,0.6,0.0,0.0,0.1,0.0,0.0,2.1,0.8,0.2,0.3,1.2,0.5,0.0,0.0,0.0,0.0,77.2,0.0,0.0,0.0,0.0,0.0
frc21,2025.0,39.8,10.3,21.6,8.8,40.7,1.1,4.8,4.9,0.0,0.0,0.0,13.4,1.00,1.0,1.0,0.0,0.0,0.1,0.0,0.0,3.8,0.3,0.0,0.7,0.0,0.0,0.0,0.8,0.0,0.0,17.3,3.9,0.0,0.0,0.0,0.0
frc3824,2025.0,38.7,5.7,16.3,5.4,27.4,0.6,1.6,1.1,0.0,2.6,2.6,21.4,1.00,0.9,0.3,0.0,0.0,0.3,0.0,0.0,0.5,0.2,0.0,0.9,0.4,2.2,0.0,0.2,0.0,0.0,51.1,29.7,0.0,0.0,0.0,0.0
frc4630,2025.0,37.4,2.8,5.6,1.0,9.4,0.0,1.5,0.0,0.1,0.0,0.1,3.3,0.75,0.8,0.0,0.0,0.0,0.0,0.0,0.1,0.0,1.2,0.2,0.1,0.0,0.0,0.2,0.7,0.1,0.0,4.8,1.5,0.3,0.1,0.0,0.0
frc5045,2025.0,39.9,4.8,10.6,1.8,17.2,0.4,3.2,0.7,0.0,0.0,0.0,32.3,0.85,0.9,0.0,0.3,0.0,0.1,0.0,0.0,0.0,2.1,0.0,1.1,0.0,0.0,0.2,0.8,0.0,0.0,33.2,0.9,0.2,0.1,0.0,0.0
frc5744,2025.0,38.0,3.4,0.0,1.2,4.6,0.1,0.0,0.1,0.0,0.0,0.0,14.1,0.80,0.9,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6,3.1,0.0,0.0,17.6,3.5,0.2,0.0,0.0,0.0